import {
  Accordion,
  ActionIcon,
  Alert,
  Badge,
  Box,
  Button,
  FileButton,
  Group,
  Loader,
  Paper,
  Progress,
  Select,
  SimpleGrid,
  Stack,
  Stepper,
  Table,
  Text,
  TextInput,
  ThemeIcon,
  Tooltip,
  UnstyledButton,
} from '@mantine/core'
import { Dropzone } from '@mantine/dropzone'
import { useForm } from '@mantine/form'
import { notifications } from '@mantine/notifications'
import {
  IconAlertCircle,
  IconAlertTriangle,
  IconCheck,
  IconFileText,
  IconFileUpload,
  IconHeartbeat,
  IconPhoto,
  IconPlus,
  IconQuestionMark,
  IconTrash,
  IconX,
} from '@tabler/icons-react'
import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

import {
  classifyEvidence,
  getModels,
  getTenantSettings,
  submitApplication,
  type ClassifyResponse,
} from '../../api/client'
import { PageHeader } from '../../components/PageHeader'
import { Section } from './components'
import { ModelFieldControls } from './ModelFields'
import {
  declaredHistory,
  DICOM,
  DOCUMENT,
  ECG_EXPORT,
  MODELS,
  PHOTO,
  bool,
  type ModelValues,
  type Scalar,
} from './models'

/**
 * Taking an application, in four steps: the client, the cover, the evidence,
 * and a last look before it is sent.
 *
 * **Evidence is dropped once.** Everything the client brought goes into the
 * one drop zone on the first step. The platform works out what each file is;
 * the evidence step then lists every file with a preview and what it was
 * identified as, where a wrong guess is corrected in place. No per-reader drop
 * zones: the files decide which readers run, and every reader's extra
 * questions are asked together in one panel below the list.
 *
 * Nothing is scored until the operator has seen what each file is, because a
 * model handed the wrong kind of document answers confidently instead of
 * failing (the retina model scores a chest X-ray 98.8). An unrecognised file
 * has to be given a kind before the application can go.
 *
 * The reference is generated by the database (`applicants_ref_seq` ->
 * `HL-<seq>`); the client's portal sign-in is shown on its own page after
 * submit, where it can also be sent again later.
 */

const MAX_FILE_BYTES = 50 * 1024 * 1024
const MAX_FACE_BYTES = 10 * 1024 * 1024

/** The latest date of birth an adult can have: today, eighteen years ago. */
function latestAdultBirthDate(): string {
  const d = new Date()
  d.setFullYear(d.getFullYear() - 18)
  return d.toISOString().slice(0, 10)
}

function isAdult(dob: string): boolean {
  return dob !== '' && dob <= latestAdultBirthDate()
}

function formatSize(b: number) {
  if (b < 1024) return `${b} B`
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(0)} KB`
  return `${(b / (1024 * 1024)).toFixed(1)} MB`
}

const taka = (n: number) => `৳${Math.round(n).toLocaleString('en-IN')}`

interface IntakeForm {
  name: string
  phone: string
  email: string
  dob: string
  sex: string | null
  coverageType: string | null
  coverageAmount: number | null
  policyTerm: string | null
  modelFields: Record<string, ModelValues>
}

/** One file the client brought, and what the platform and the operator say it is. */
interface EvidenceItem {
  id: string
  file: File
  /** What the platform proposed. `unknown` until it has answered. */
  proposed: string
  /** What it is now: the proposal, or the operator's correction. */
  kind: string
  reason: string
  thumbnail: string | null
  /** The platform was not sure; worth a second look, not a block. */
  unsure: boolean
  reading: boolean
}

/** Files set aside because they fill in the form rather than being evidence. */
interface SetAside {
  name: string
  what: string
}

const COVER_TYPES = [
  {
    value: 'Life',
    title: 'Life cover',
    text: 'Pays the full amount to the family if the client dies during the term.',
  },
  {
    value: 'Health',
    title: 'Health cover',
    text: 'Pays hospital and treatment bills, up to the amount, in each year of the policy.',
  },
  {
    value: 'Critical illness',
    title: 'Critical illness cover',
    text: 'Pays the full amount once if the client is diagnosed with a covered serious illness, such as cancer, a heart attack or a stroke.',
  },
]

const TERMS = ['5', '10', '15', '20', '25']

export function IntakePage() {
  const navigate = useNavigate()
  const form = useForm<IntakeForm>({
    initialValues: {
      name: '',
      phone: '',
      email: '',
      dob: '',
      sex: null,
      coverageType: null,
      coverageAmount: null,
      policyTerm: '10',
      modelFields: {},
    },
  })

  const { data: policy } = useQuery({ queryKey: ['tenant-settings'], queryFn: getTenantSettings })
  const reference = policy?.referenceCoverBdt ?? 1_000_000
  const rateStandard = policy?.premiumLowBdt ?? 5_000
  const rateAdjusted = policy?.premiumModerateBdt ?? 7_500
  const premiumFor = (amount: number, rate: number) => Math.round((rate * amount) / reference)
  const amounts = [0.25, 0.5, 1, 1.5, 2, 3, 5, 10].map(
    (m) => Math.round((reference * m) / 50_000) * 50_000,
  )

  const { data: catalogue = [] } = useQuery({ queryKey: ['models'], queryFn: getModels, staleTime: 5 * 60 * 1000 })
  const availability = new Map(catalogue.map((m) => [m.id, m]))
  const isAvailable = (id: string) => availability.get(id)?.available ?? false
  const readerName = (id: string) => availability.get(id)?.label ?? MODELS.find((m) => m.id === id)?.label ?? id

  const [step, setStep] = useState(0)
  const [evidence, setEvidence] = useState<EvidenceItem[]>([])
  const [choices, setChoices] = useState<ClassifyResponse['choices']>([])
  const [setAside, setSetAside] = useState<SetAside[]>([])
  // Readers that take typed values and no file (the blood panel), switched on
  // by hand or by a dropped blood-panel.json.
  const [formReaders, setFormReaders] = useState<string[]>([])
  const [facePhoto, setFacePhoto] = useState<File | null>(null)
  const [facePreview, setFacePreview] = useState<string | null>(null)
  const [submitting, setSubmitting] = useState(false)
  const [submitError, setSubmitError] = useState<string | null>(null)

  const kindLabel = (kind: string) =>
    kind === 'unknown' ? 'Not recognised' : ((choices ?? []).find((c) => c.kind === kind)?.label ?? kind)
  const readerFor = (kind: string): string | null =>
    ((choices ?? []).find((c) => c.kind === kind)?.arms ?? []).find((arm) => isAvailable(arm)) ?? null

  // Which readers run follows from the files, never from a separate picker.
  const fileReaders = [...new Set(evidence.map((e) => readerFor(e.kind)).filter((r): r is string => Boolean(r)))]
  const activeReaders = [...fileReaders, ...formReaders.filter((r) => isAvailable(r) && !fileReaders.includes(r))]
  const activeDefs = MODELS.filter((m) => activeReaders.includes(m.id))

  const setFields = (modelId: string, values: Record<string, Scalar>) =>
    form.setFieldValue('modelFields', (current: Record<string, ModelValues>) => ({
      ...current,
      [modelId]: { ...(current[modelId] ?? {}), ...values },
    }))
  const setField = (modelId: string, key: string, value: Scalar) => setFields(modelId, { [key]: value })
  const toggleSet = (modelId: string, key: string, value: string) =>
    form.setFieldValue('modelFields', (current: Record<string, ModelValues>) => {
      const list = (current[modelId]?.[key] as string[]) ?? []
      return {
        ...current,
        [modelId]: {
          ...(current[modelId] ?? {}),
          [key]: list.includes(value) ? list.filter((v) => v !== value) : [...list, value],
        },
      }
    })

  /**
   * A client's folder can carry files that fill in the form rather than being
   * evidence: `client.json` (the client and the cover) and `blood-panel.json`
   * (the lab values). A README describing the folder is set aside. Everything
   * else is evidence.
   */
  const takeFormFiles = async (files: File[]): Promise<File[]> => {
    const rest: File[] = []
    for (const file of files) {
      const name = file.name.toLowerCase()
      if (name.endsWith('.md')) {
        setSetAside((p) => [...p, { name: file.name, what: 'Notes about the folder: not evidence, not read' }])
        continue
      }
      if (!name.endsWith('.json')) {
        rest.push(file)
        continue
      }
      try {
        const data = JSON.parse(await file.text()) as Record<string, unknown>
        if (typeof data.name === 'string' || typeof data.phone === 'string') {
          const cover = (data.coverage ?? {}) as Record<string, unknown>
          form.setValues((v) => ({
            name: typeof data.name === 'string' ? data.name : v.name,
            phone: typeof data.phone === 'string' ? data.phone : v.phone,
            email: typeof data.email === 'string' ? data.email : v.email,
            dob: typeof data.dateOfBirth === 'string' ? data.dateOfBirth : v.dob,
            sex: typeof data.sex === 'string' ? data.sex : v.sex,
            coverageType: typeof cover.type === 'string' ? cover.type : v.coverageType,
            coverageAmount: typeof cover.amount === 'number' ? cover.amount : v.coverageAmount,
            policyTerm: typeof cover.term === 'string' ? cover.term : v.policyTerm,
          }))
          const questions = (data.questions ?? {}) as Record<string, Record<string, Scalar>>
          for (const [modelId, values] of Object.entries(questions)) {
            setFields(modelId, values)
            const def = MODELS.find((m) => m.id === modelId)
            if (def && def.upload === null) setFormReaders((p) => (p.includes(modelId) ? p : [...p, modelId]))
          }
          setSetAside((p) => [...p, { name: file.name, what: 'Filled in the client, the cover and their answers' }])
        } else if ('albumin_g_dl' in data || 'creatinine_mg_dl' in data) {
          setFields('xgboost', data as Record<string, Scalar>)
          setFormReaders((p) => (p.includes('xgboost') ? p : [...p, 'xgboost']))
          setSetAside((p) => [...p, { name: file.name, what: 'Blood panel values, typed in for you' }])
        } else {
          rest.push(file)
        }
      } catch {
        rest.push(file)
      }
    }
    return rest
  }

  /**
   * Add files: every one appears at once as a tile, and each is identified on
   * its own, three at a time, so the tiles tick off one by one and the
   * progress bar counts real answers rather than spinning on one big request.
   */
  const addFiles = async (all: File[]) => {
    const files = await takeFormFiles(all)
    if (files.length === 0) return
    const added: EvidenceItem[] = files.map((file) => ({
      id: crypto.randomUUID(),
      file,
      proposed: 'unknown',
      kind: 'unknown',
      reason: 'Reading the file…',
      thumbnail: null,
      unsure: false,
      reading: true,
    }))
    setEvidence((p) => [...p, ...added])

    const failed: string[] = []
    const identify = async (item: EvidenceItem) => {
      try {
        const result = await classifyEvidence([item.file])
        if (result.choices?.length) setChoices(result.choices)
        const found = result.files[0]
        setEvidence((p) =>
          p.map((e) =>
            e.id !== item.id
              ? e
              : found
                ? {
                    ...e,
                    proposed: found.kind,
                    kind: found.kind,
                    reason: found.reason,
                    thumbnail: found.thumbnail ?? null,
                    unsure: found.needsChoice,
                    reading: false,
                  }
                : { ...e, reading: false, reason: 'Could not be read. Choose what it is.' },
          ),
        )
      } catch {
        failed.push(item.file.name)
        setEvidence((p) =>
          p.map((e) => (e.id === item.id ? { ...e, reading: false, reason: 'Could not be identified. Choose what it is.' } : e)),
        )
      }
    }
    const queue = [...added]
    await Promise.all(
      Array.from({ length: Math.min(3, queue.length) }, async () => {
        for (let next = queue.shift(); next; next = queue.shift()) await identify(next)
      }),
    )
    notifications.show({
      title: failed.length
        ? `${added.length - failed.length} of ${added.length} files identified`
        : `${added.length} file${added.length === 1 ? '' : 's'} identified`,
      message: failed.length
        ? `Could not identify ${failed.join(', ')}. Choose what ${failed.length === 1 ? 'it is' : 'they are'} on the Evidence step.`
        : 'Check what each one is on the Evidence step.',
      color: failed.length ? 'yellow' : 'teal',
    })
  }

  const setKind = (id: string, kind: string) =>
    setEvidence((p) => p.map((e) => (e.id === id ? { ...e, kind } : e)))
  const removeFile = (id: string) => setEvidence((p) => p.filter((e) => e.id !== id))

  const setFace = (file: File | null) => {
    if (facePreview) URL.revokeObjectURL(facePreview)
    setFacePhoto(file)
    setFacePreview(file ? URL.createObjectURL(file) : null)
  }

  // ── what each step needs ──────────────────────────────────────────────────
  const reading = evidence.some((e) => e.reading)
  const unresolved = evidence.filter((e) => !e.reading && e.kind === 'unknown')
  const mammograms = evidence.filter((e) => e.kind === 'mammogram').length
  const tbFollowUpAnswered = (() => {
    if (!activeReaders.includes('cxr_lung')) return true
    const v = form.values.modelFields.cxr_lung
    if (!bool(v?.prior_tb)) return true
    return v?.prior_tb_treatment_completed === 'yes' || v?.prior_tb_treatment_completed === 'no'
  })()

  const clientDone =
    Boolean(form.values.name.trim()) &&
    Boolean(form.values.phone.trim()) &&
    (form.values.dob === '' || isAdult(form.values.dob))
  const coverDone =
    Boolean(form.values.coverageType) && (form.values.coverageAmount ?? 0) > 0 && Boolean(form.values.policyTerm)
  const evidenceDone = activeReaders.length > 0 && !reading && unresolved.length === 0 && tbFollowUpAnswered
  const done = [clientDone, coverDone, evidenceDone]

  const sendApplication = async () => {
    setSubmitting(true)
    setSubmitError(null)
    try {
      const result = await submitApplication({
        payload: {
          applicant: {
            name: form.values.name.trim(),
            phone: form.values.phone.trim(),
            dateOfBirth: form.values.dob || null,
            sex: form.values.sex,
            email: form.values.email.trim() || null,
          },
          coverage: {
            coverageType: form.values.coverageType,
            coverageAmount: form.values.coverageAmount,
            policyTerm: form.values.policyTerm,
          },
          modelsRequested: activeReaders,
          declaredHistory: declaredHistory(activeReaders, form.values.modelFields),
        },
        // A file whose kind no reader takes is still sent: it is stored for
        // the underwriter to read, and simply not scored.
        files: evidence.map((e) => ({ file: e.file, arm: readerFor(e.kind) ?? '', kind: e.kind })),
        facePhoto,
      })
      // The client's sign-in has its own page, which can be come back to.
      navigate(`/applications/${result.id}/sign-in`, {
        replace: true,
        state: { portal: result.portal, justSubmitted: true },
      })
    } catch (err) {
      // Keep the form exactly as it was: the client is sitting opposite.
      setSubmitError(err instanceof Error ? err.message : 'The application could not be submitted.')
    } finally {
      setSubmitting(false)
    }
  }

  // ── pieces ────────────────────────────────────────────────────────────────
  const dropZone = (
    <Dropzone
      onDrop={(files) => void addFiles(files)}
      onReject={(rejects) => {
        const real = rejects.filter((r) => !r.file.name.toLowerCase().endsWith('.md'))
        if (real.length === 0) return
        notifications.show({
          title: `${real.length} file${real.length === 1 ? '' : 's'} not accepted`,
          message: real
            .map((r) =>
              r.file.size > MAX_FILE_BYTES ? `${r.file.name}: larger than 50 MB` : `${r.file.name}: not a type the platform reads`,
            )
            .concat('Images, DICOM, ECG exports (.csv), PDF and text up to 50 MB.')
            .join('\n'),
          color: 'red',
          style: { whiteSpace: 'pre-line' },
        })
      }}
      accept={{ ...DICOM, ...PHOTO, ...DOCUMENT, ...ECG_EXPORT, 'application/json': ['.json'] }}
      maxSize={MAX_FILE_BYTES}
      multiple
      className="drop-all"
    >
      <Group justify="center" gap="md" style={{ pointerEvents: 'none' }} py={evidence.length > 0 ? 'sm' : 'lg'}>
        <Dropzone.Accept>
          <IconCheck size={30} stroke={1.6} style={{ color: 'var(--neo-forest)' }} />
        </Dropzone.Accept>
        <Dropzone.Reject>
          <IconX size={30} stroke={1.6} style={{ color: 'var(--neo-danger)' }} />
        </Dropzone.Reject>
        <Dropzone.Idle>
          <IconFileUpload size={30} stroke={1.4} style={{ color: 'var(--neo-accent)' }} />
        </Dropzone.Idle>
        <div>
          <Dropzone.Accept>
            <Text size="sm" fw={700}>
              Let go to add them
            </Text>
          </Dropzone.Accept>
          <Dropzone.Reject>
            <Text size="sm" fw={700} c="red">
              Some of these cannot be read
            </Text>
          </Dropzone.Reject>
          <Dropzone.Idle>
            <Text size="sm" fw={600}>
              {evidence.length > 0 ? 'Drop more files here, or click to add them' : 'Drop every file the client brought here'}
            </Text>
          </Dropzone.Idle>
          <Text size="xs" style={{ color: 'var(--neo-muted)' }}>
            Scans, retinal photos, mammograms, ECG exports, reports, or the whole folder. Each file is
            identified for you.
          </Text>
        </div>
      </Group>
    </Dropzone>
  )

  const amount = form.values.coverageAmount ?? 0
  const years = Number(form.values.policyTerm ?? 0)
  const standard = amount ? premiumFor(amount, rateStandard) : 0
  const adjusted = amount ? premiumFor(amount, rateAdjusted) : 0

  return (
    <Stack gap="lg" maw={1080}>
      <PageHeader screen="intake" />

      <Stepper active={step} onStepClick={setStep} allowNextStepsSelect={false} size="sm" completedIcon={<IconCheck size={16} />}>
        {/* ── 1. Client ───────────────────────────────────────── */}
        <Stepper.Step label="Client" description="Who is applying">
          <div key="client" className="page-enter">
            <Text size="sm" mt="md" mb="xs" style={{ color: 'var(--neo-muted)' }}>
              Have the client's folder? Drop everything in it here. Their details and cover are filled in
              from it, and every file is identified.
            </Text>
            {dropZone}
            <UploadSummary
              evidence={evidence}
              setAside={setAside}
              kindLabel={kindLabel}
              onRemove={removeFile}
            />
            <Section n="1" title="The client" complete={clientDone}>
              <SimpleGrid cols={{ base: 1, md: 2 }} spacing="lg">
                <Stack gap="sm">
                  <Group grow align="flex-start">
                    <TextInput label="Name" required placeholder="Client name" {...form.getInputProps('name')} />
                    <TextInput label="Phone" required placeholder="+880 1XXXXXXXXX" {...form.getInputProps('phone')} />
                  </Group>
                  <TextInput
                    label="Email"
                    type="email"
                    placeholder="client@example.com"
                    description="Their portal sign-in is sent here. Without it, you are shown the sign-in to hand over."
                    {...form.getInputProps('email')}
                  />
                  <Group grow align="flex-start">
                    <TextInput
                      label="Date of birth"
                      type="date"
                      description="The client must be 18 or over"
                      max={latestAdultBirthDate()}
                      min="1900-01-01"
                      {...form.getInputProps('dob')}
                      error={form.values.dob && !isAdult(form.values.dob) ? 'The client must be at least 18' : undefined}
                    />
                    <Select
                      label="Sex"
                      placeholder="Prefer not to say"
                      data={['Female', 'Male', 'Other', 'Prefer not to say']}
                      clearable
                      {...form.getInputProps('sex')}
                    />
                  </Group>
                </Stack>
                <FacePhoto file={facePhoto} preview={facePreview} onFile={setFace} />
              </SimpleGrid>
            </Section>
          </div>
        </Stepper.Step>

        {/* ── 2. Cover ────────────────────────────────────────── */}
        <Stepper.Step label="Cover" description="What they are asking for" allowStepSelect={step > 1}>
          <div key="cover" className="page-enter">
            <Section n="2" title="The cover they want" complete={coverDone}>
              <Text size="sm" fw={600}>
                1. What should the policy pay for?
              </Text>
              <SimpleGrid cols={{ base: 1, sm: 3 }} spacing="sm">
                {COVER_TYPES.map((c) => (
                  <ChoiceCard
                    key={c.value}
                    selected={form.values.coverageType === c.value}
                    onClick={() => form.setFieldValue('coverageType', c.value)}
                    title={c.title}
                    text={c.text}
                  />
                ))}
              </SimpleGrid>

              <Text size="sm" fw={600} mt="sm">
                2. How much should it pay out?
              </Text>
              <Text size="xs" c="dimmed" mt={-8}>
                The amount paid on a claim (the sum assured), with what it costs each month at your standard
                rate. The final price is set by the underwriter after the health check.
              </Text>
              <SimpleGrid cols={{ base: 2, sm: 4 }} spacing="sm">
                {amounts.map((a) => (
                  <ChoiceCard
                    key={a}
                    selected={form.values.coverageAmount === a}
                    onClick={() => form.setFieldValue('coverageAmount', a)}
                    title={`Pays ${taka(a)}`}
                    text={`from ${taka(premiumFor(a, rateStandard))} a month`}
                  />
                ))}
              </SimpleGrid>

              <Text size="sm" fw={600} mt="sm">
                3. For how many years?
              </Text>
              <Group gap="xs">
                {TERMS.map((t) => (
                  <Button
                    key={t}
                    size="xs"
                    variant={form.values.policyTerm === t ? 'filled' : 'default'}
                    onClick={() => form.setFieldValue('policyTerm', t)}
                  >
                    {t} years
                  </Button>
                ))}
              </Group>

              {coverDone && (
                <Paper p="md" mt="sm" bd="1px solid var(--neo-forest)" bg="var(--neo-accent-soft)">
                  <Text size="xs" tt="uppercase" fw={700} lts={0.5} c="dimmed">
                    What this means for the client
                  </Text>
                  <SimpleGrid cols={{ base: 2, sm: 4 }} mt="xs" spacing="md">
                    <Figure label="Pays out on a claim" value={taka(amount)} />
                    <Figure label="They pay each month" value={`from ${taka(standard)}`} />
                    <Figure label="Each year" value={`from ${taka(standard * 12)}`} />
                    <Figure label={`Over ${years} years`} value={`from ${taka(standard * 12 * years)}`} />
                  </SimpleGrid>
                  <Text size="xs" mt="sm">
                    {form.values.coverageType === 'Life'
                      ? `If the client dies within the ${years} years, the family is paid ${taka(amount)}.`
                      : form.values.coverageType === 'Health'
                        ? `Each year for ${years} years, hospital and treatment bills are paid up to ${taka(amount)}.`
                        : `If the client is diagnosed with a covered serious illness within ${years} years, they are paid ${taka(amount)} once.`}{' '}
                    The monthly price is the standard rate. If the health check finds a moderate risk it may
                    be about {taka(adjusted)} a month; an elevated risk goes to a doctor first and has no price
                    until then. Payments stop and the cover ends after {years} years, or if the policy is
                    cancelled.
                  </Text>
                </Paper>
              )}
            </Section>
          </div>
        </Stepper.Step>

        {/* ── 3. Evidence ─────────────────────────────────────── */}
        <Stepper.Step label="Evidence" description="Check each file" allowStepSelect={step > 2}>
          <div key="evidence" className="page-enter">
            <Section n="3" title="What the client brought" complete={evidenceDone}>
              <Group justify="space-between" align="center">
                <Text size="sm" c="dimmed">
                  {evidence.length === 0
                    ? 'No files yet. Add them here, or drop them on the Client step.'
                    : `${evidence.length} file${evidence.length === 1 ? '' : 's'} · ${activeReaders.length} reader${activeReaders.length === 1 ? '' : 's'} will run. Change anything identified wrongly.`}
                </Text>
                <Group gap="xs">
                  <FileButton onChange={(files) => void addFiles(files)} multiple>
                    {(props) => (
                      <Button {...props} size="xs" variant="light" leftSection={<IconPlus size={14} />}>
                        Add files
                      </Button>
                    )}
                  </FileButton>
                  {!activeReaders.includes('xgboost') && isAvailable('xgboost') && (
                    <Button size="xs" variant="default" onClick={() => setFormReaders((p) => [...p, 'xgboost'])}>
                      Add blood panel and lifestyle
                    </Button>
                  )}
                </Group>
              </Group>

              {evidence.length > 0 && (
                <Box style={{ border: '1px solid var(--neo-border-mid)', borderRadius: 8, overflow: 'hidden' }}>
                  <Table verticalSpacing="sm" highlightOnHover>
                    <Table.Thead>
                      <Table.Tr>
                        <Table.Th w={76}>Preview</Table.Th>
                        <Table.Th>File</Table.Th>
                        <Table.Th w={260}>Identified as</Table.Th>
                        <Table.Th>Read by</Table.Th>
                        <Table.Th w={44} />
                      </Table.Tr>
                    </Table.Thead>
                    <Table.Tbody>
                      {evidence.map((e) => {
                        const reader = readerFor(e.kind)
                        const corrected = !e.reading && e.kind !== e.proposed && e.proposed !== 'unknown'
                        return (
                          <Table.Tr
                            key={e.id}
                            style={{ backgroundColor: !e.reading && e.kind === 'unknown' ? 'var(--neo-warn-soft)' : undefined }}
                          >
                            <Table.Td>
                              <Preview item={e} />
                            </Table.Td>
                            <Table.Td>
                              <Text size="sm" fw={600} className="hl-ellipsis" maw={260}>
                                {e.file.name}
                              </Text>
                              <Text size="xs" c="dimmed">
                                {formatSize(e.file.size)} · {e.reason}
                              </Text>
                            </Table.Td>
                            <Table.Td>
                              {e.reading ? (
                                <Group gap={6}>
                                  <Loader size={12} />
                                  <Text size="xs" c="dimmed">
                                    Identifying…
                                  </Text>
                                </Group>
                              ) : (
                                <Stack gap={4}>
                                  <Select
                                    size="xs"
                                    aria-label={`What ${e.file.name} is`}
                                    value={e.kind === 'unknown' ? null : e.kind}
                                    placeholder="Choose what this is"
                                    data={(choices ?? [])
                                      .filter((c) => c.kind !== 'unknown')
                                      .map((c) => ({ value: c.kind, label: c.label }))}
                                    onChange={(v) => v && setKind(e.id, v)}
                                    error={e.kind === 'unknown' ? 'Not recognised. Choose one.' : undefined}
                                    allowDeselect={false}
                                  />
                                  {corrected && (
                                    <Badge size="xs" variant="light" color="yellow">
                                      Corrected (was {kindLabel(e.proposed)})
                                    </Badge>
                                  )}
                                  {!corrected && e.unsure && e.kind !== 'unknown' && (
                                    <Badge size="xs" variant="light" color="orange">
                                      Not certain: please check
                                    </Badge>
                                  )}
                                </Stack>
                              )}
                            </Table.Td>
                            <Table.Td>
                              {e.reading ? null : reader ? (
                                <Badge size="sm" variant="light" color="teal" style={{ minWidth: 'max-content' }}>
                                  {readerName(reader)}
                                </Badge>
                              ) : e.kind === 'unknown' ? (
                                <Text size="xs" c="dimmed">
                                  —
                                </Text>
                              ) : (
                                <Text size="xs" c="dimmed">
                                  Stored for the underwriter; no model reads it
                                </Text>
                              )}
                            </Table.Td>
                            <Table.Td>
                              <Tooltip label="Remove this file" withArrow>
                                <ActionIcon variant="subtle" color="red" onClick={() => removeFile(e.id)} aria-label={`Remove ${e.file.name}`}>
                                  <IconTrash size={15} />
                                </ActionIcon>
                              </Tooltip>
                            </Table.Td>
                          </Table.Tr>
                        )
                      })}
                    </Table.Tbody>
                  </Table>
                </Box>
              )}

              {setAside.length > 0 && (
                <Text size="xs" c="dimmed">
                  Also in the folder:{' '}
                  {setAside.map((s, i) => (
                    <span key={`${s.name}-${i}`}>
                      {i > 0 && ' · '}
                      <Text span ff="monospace" size="xs">
                        {s.name}
                      </Text>{' '}
                      ({s.what})
                    </span>
                  ))}
                </Text>
              )}

              {unresolved.length > 0 && (
                <Alert color="yellow" variant="light" icon={<IconAlertTriangle size={16} />}>
                  <Text size="sm">
                    {unresolved.length === 1 ? 'One file was' : `${unresolved.length} files were`} not recognised.
                    Choose what each is, or Document to store it for the underwriter without scoring it.
                  </Text>
                </Alert>
              )}
              {mammograms > 0 && mammograms !== 4 && (
                <Alert color="yellow" variant="light" icon={<IconAlertTriangle size={16} />}>
                  <Text size="sm">
                    The mammogram model reads all four views together (left and right, from above and the
                    side). {mammograms} of 4 are here.
                  </Text>
                </Alert>
              )}

              {activeDefs.length > 0 && (
                <Box mt="xs">
                  <Text size="sm" fw={700}>
                    Additional information
                  </Text>
                  <Text size="xs" c="dimmed" mb="xs">
                    What each reader asks besides the file. Everything here is optional unless marked; answers
                    from the client's folder are already filled in.
                  </Text>
                  <Accordion multiple defaultValue={activeDefs.map((m) => m.id)} variant="separated" radius="md">
                    {activeDefs.map((m) => (
                      <Accordion.Item key={m.id} value={m.id}>
                        <Accordion.Control>
                          <Group gap="xs">
                            <Text size="sm" fw={600}>
                              {readerName(m.id)}
                            </Text>
                            <Text size="xs" c="dimmed">
                              {availability.get(m.id)?.screensFor ?? m.modality}
                            </Text>
                            {m.upload === null && (
                              <Button
                                component="span"
                                size="compact-xs"
                                variant="subtle"
                                color="red"
                                onClick={(ev) => {
                                  ev.stopPropagation()
                                  setFormReaders((p) => p.filter((r) => r !== m.id))
                                }}
                              >
                                Remove
                              </Button>
                            )}
                          </Group>
                        </Accordion.Control>
                        <Accordion.Panel>
                          <ModelFieldControls
                            model={m}
                            values={form.values.modelFields[m.id] ?? {}}
                            setField={setField}
                            toggleSet={toggleSet}
                          />
                        </Accordion.Panel>
                      </Accordion.Item>
                    ))}
                  </Accordion>
                </Box>
              )}
              {!tbFollowUpAnswered && (
                <Text size="xs" c="red">
                  Chest X-ray: say whether the TB treatment was completed.
                </Text>
              )}
            </Section>
          </div>
        </Stepper.Step>

        {/* ── 4. Review and submit ────────────────────────────── */}
        <Stepper.Step label="Submit" description="A last look">
          <div key="submit" className="page-enter">
            <Section n="4" title="Ready to submit" complete={done.every(Boolean)}>
              {!done.every(Boolean) ? (
                <Alert color="yellow" variant="light" icon={<IconAlertTriangle size={16} />} title="Something still needs doing">
                  <Stack gap={4}>
                    {!clientDone && (
                      <Group justify="space-between">
                        <Text size="sm">The client needs a name and a phone number.</Text>
                        <Button size="compact-xs" variant="light" onClick={() => setStep(0)}>Fix</Button>
                      </Group>
                    )}
                    {!coverDone && (
                      <Group justify="space-between">
                        <Text size="sm">Choose the cover, the amount and the years.</Text>
                        <Button size="compact-xs" variant="light" onClick={() => setStep(1)}>Fix</Button>
                      </Group>
                    )}
                    {!evidenceDone && (
                      <Group justify="space-between">
                        <Text size="sm">
                          {activeReaders.length === 0
                            ? 'Add at least one file or the blood panel.'
                            : reading
                              ? 'Files are still being identified.'
                              : unresolved.length > 0
                                ? 'Some files are not identified yet.'
                                : 'A question about TB treatment is unanswered.'}
                        </Text>
                        <Button size="compact-xs" variant="light" onClick={() => setStep(2)}>Fix</Button>
                      </Group>
                    )}
                  </Stack>
                </Alert>
              ) : (
                <SimpleGrid cols={{ base: 1, md: 3 }} spacing="md">
                  <Summary title="Client">
                    <Text size="sm" fw={600}>{form.values.name}</Text>
                    <Text size="xs" c="dimmed">
                      {form.values.phone}
                      {form.values.email ? ` · ${form.values.email}` : ' · no email: you will be shown their sign-in'}
                    </Text>
                  </Summary>
                  <Summary title="Cover">
                    <Text size="sm" fw={600}>
                      {form.values.coverageType} · pays {taka(amount)} · {years} years
                    </Text>
                    <Text size="xs" c="dimmed">from {taka(standard)} a month at the standard rate</Text>
                  </Summary>
                  <Summary title="Readers">
                    <Group gap={4}>
                      {activeReaders.map((r) => (
                        <Badge key={r} size="sm" variant="light" color="teal">{readerName(r)}</Badge>
                      ))}
                    </Group>
                  </Summary>
                </SimpleGrid>
              )}

              {evidence.length > 0 && (
                <Group gap="xs">
                  {evidence.map((e) => (
                    <Paper key={e.id} p={6} pr="sm" bd="1px solid var(--neo-border-mid)">
                      <Group gap={8} wrap="nowrap">
                        <Preview item={e} size={36} />
                        <div>
                          <Text size="xs" fw={600} className="hl-ellipsis" maw={180}>{e.file.name}</Text>
                          <Text size="xs" c="dimmed">{kindLabel(e.kind)}</Text>
                        </div>
                      </Group>
                    </Paper>
                  ))}
                </Group>
              )}

              <Group justify="flex-end">
                <Button size="md" onClick={() => void sendApplication()} loading={submitting} disabled={!done.every(Boolean)}>
                  Submit application
                </Button>
              </Group>
            </Section>
          </div>
        </Stepper.Step>
      </Stepper>

      {submitError && (
        <Alert color="red" variant="light" icon={<IconAlertCircle size={16} />} title="The application was not submitted">
          <Text size="sm">{submitError}</Text>
          <Text size="xs" c="dimmed" mt={4}>
            Nothing has been lost. Everything you entered is still here. Try again.
          </Text>
        </Alert>
      )}

      {step < 3 && (
        <Group justify="space-between" align="center">
          <Button variant="subtle" size="sm" disabled={step === 0} onClick={() => setStep(step - 1)}>
            Back
          </Button>
          <Group gap="sm" align="center">
            <Text size="xs" c="dimmed" ta="right" maw={420}>
              {step === 0 && 'A name and a phone number are needed. Everything else here is optional.'}
              {step === 1 && 'What it pays for, how much, and for how long.'}
              {step === 2 && 'Every file needs a kind. Nothing is scored until you submit.'}
            </Text>
            <Button size="sm" disabled={!done[step]} onClick={() => setStep(step + 1)}>
              Continue
            </Button>
          </Group>
        </Group>
      )}
    </Stack>
  )
}

/** A file's thumbnail, or an icon for what it is when there is no picture. */
function Preview({ item, size = 56 }: { item: EvidenceItem; size?: number }) {
  if (item.thumbnail) {
    return (
      <Box w={size} h={size} style={{ borderRadius: 6, overflow: 'hidden', background: '#000', flexShrink: 0 }}>
        <img src={item.thumbnail} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
      </Box>
    )
  }
  const Icon =
    item.kind === 'ecg' ? IconHeartbeat : item.kind === 'document' ? IconFileText : item.kind === 'unknown' ? IconQuestionMark : IconPhoto
  return (
    <ThemeIcon size={size} radius="md" variant="light" color={!item.reading && item.kind === 'unknown' ? 'yellow' : 'gray'}>
      {item.reading ? <Loader size={size / 3} /> : <Icon size={size / 2.4} />}
    </ThemeIcon>
  )
}

function ChoiceCard({
  selected,
  onClick,
  title,
  text,
}: {
  selected: boolean
  onClick: () => void
  title: string
  text: string
}) {
  return (
    <UnstyledButton
      onClick={onClick}
      p="sm"
      style={{
        border: `1.5px solid ${selected ? 'var(--neo-forest)' : 'var(--neo-border-mid)'}`,
        background: selected ? 'var(--neo-accent-soft)' : 'var(--neo-card)',
        borderRadius: 8,
        textAlign: 'left',
      }}
      aria-pressed={selected}
    >
      <Group gap={6} wrap="nowrap" align="flex-start">
        {selected && <IconCheck size={15} style={{ color: 'var(--neo-forest)', marginTop: 2, flexShrink: 0 }} />}
        <div>
          <Text size="sm" fw={700}>
            {title}
          </Text>
          <Text size="xs" c="dimmed" mt={2}>
            {text}
          </Text>
        </div>
      </Group>
    </UnstyledButton>
  )
}

function Figure({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <Text size="xs" c="dimmed">
        {label}
      </Text>
      <Text fw={700}>{value}</Text>
    </div>
  )
}

function Summary({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <Paper p="sm" bd="1px solid var(--neo-border-mid)">
      <Text size="xs" tt="uppercase" fw={700} lts={0.5} c="dimmed" mb={4}>
        {title}
      </Text>
      {children}
    </Paper>
  )
}

/** The identity photo: optional, never read by a model, never shown beside a score. */
function FacePhoto({
  file,
  preview,
  onFile,
}: {
  file: File | null
  preview: string | null
  onFile: (file: File | null) => void
}) {
  return (
    <Paper bd="1px solid var(--mantine-color-default-border)" p="md">
      <Group gap="xs" mb={4}>
        <Text fw={600} size="sm">
          Identity photo
        </Text>
        <Badge size="xs" color="gray" variant="outline">
          Optional
        </Badge>
      </Group>
      <Text size="xs" c="dimmed" mb="sm">
        For your own records only. No model reads it, and it is never shown next to the risk score.
      </Text>
      {file && preview ? (
        <Group align="flex-start" gap="md">
          <Box w={96} h={96} style={{ borderRadius: 6, overflow: 'hidden', border: '1px solid var(--mantine-color-default-border)' }}>
            <img src={preview} alt="Face photo preview" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
          </Box>
          <Stack gap={4} align="flex-start">
            <Text ff="monospace" size="sm">
              {file.name}
            </Text>
            <Button size="xs" variant="subtle" color="red" onClick={() => onFile(null)}>
              Remove
            </Button>
          </Stack>
        </Group>
      ) : (
        <FileButton
          accept="image/png,image/jpeg"
          onChange={(f) => {
            if (f && f.size > MAX_FACE_BYTES) {
              notifications.show({ title: 'Photo too large', message: 'Up to 10 MB.', color: 'red' })
              return
            }
            onFile(f)
          }}
        >
          {(props) => (
            <Button {...props} size="xs" variant="default">
              Choose a photo (.png or .jpg)
            </Button>
          )}
        </FileButton>
      )}
    </Paper>
  )
}

/**
 * What the drop did, right under the drop zone: a tile per file that turns from
 * "reading" to what it was identified as, a bar counting them off, and the
 * files that filled in the form instead of being evidence.
 */
function UploadSummary({
  evidence,
  setAside,
  kindLabel,
  onRemove,
}: {
  evidence: EvidenceItem[]
  setAside: SetAside[]
  kindLabel: (kind: string) => string
  onRemove: (id: string) => void
}) {
  if (evidence.length === 0 && setAside.length === 0) return null
  const done = evidence.filter((e) => !e.reading).length
  const unknown = evidence.filter((e) => !e.reading && e.kind === 'unknown').length
  const reading = done < evidence.length
  const percent = evidence.length ? Math.round((done / evidence.length) * 100) : 100

  return (
    <Paper mt="sm" p="md" bd={`1px solid ${reading ? 'var(--neo-border-mid)' : unknown ? 'var(--neo-warn)' : 'var(--neo-forest)'}`}>
      <Group justify="space-between" mb={6} wrap="nowrap">
        <Group gap={8} wrap="nowrap">
          {reading ? (
            <Loader size={18} />
          ) : unknown ? (
            <IconAlertTriangle size={20} style={{ color: 'var(--neo-warn)' }} />
          ) : (
            <ThemeIcon size={22} radius="xl" color="teal">
              <IconCheck size={14} />
            </ThemeIcon>
          )}
          <div>
            <Text size="sm" fw={700}>
              {reading
                ? `Identifying ${evidence.length} file${evidence.length === 1 ? '' : 's'}… ${done} done`
                : unknown
                  ? `${evidence.length} files added · ${unknown} need${unknown === 1 ? 's' : ''} you to say what ${unknown === 1 ? 'it is' : 'they are'}`
                  : `${evidence.length} file${evidence.length === 1 ? '' : 's'} added and identified`}
            </Text>
            <Text size="xs" c="dimmed">
              {reading ? 'You can carry on filling in the form while this runs.' : 'You check each one on the Evidence step before anything is scored.'}
            </Text>
          </div>
        </Group>
        {evidence.length > 0 && (
          <Text size="sm" fw={700} ff="monospace" c={reading ? undefined : 'teal'}>
            {done}/{evidence.length}
          </Text>
        )}
      </Group>
      {evidence.length > 0 && (
        <Progress value={percent} size="sm" radius="xl" color={unknown && !reading ? 'yellow' : 'teal'} animated={reading} striped={reading} mb="sm" />
      )}

      {evidence.length > 0 && (
        <SimpleGrid cols={{ base: 1, xs: 2, md: 4 }} spacing="xs">
          {evidence.map((e) => (
            <Box
              key={e.id}
              p={6}
              className="upload-tile"
              data-state={e.reading ? 'reading' : e.kind === 'unknown' ? 'unknown' : 'done'}
            >
              <Group gap={8} wrap="nowrap">
                <Preview item={e} size={40} />
                <Box style={{ minWidth: 0, flex: 1 }}>
                  <Text size="xs" fw={600} className="hl-ellipsis">
                    {e.file.name}
                  </Text>
                  <Group gap={4} wrap="nowrap">
                    {e.reading ? (
                      <Text size="xs" c="dimmed">
                        Reading…
                      </Text>
                    ) : e.kind === 'unknown' ? (
                      <Text size="xs" c="orange" fw={600}>
                        Not recognised
                      </Text>
                    ) : (
                      <>
                        <IconCheck size={12} style={{ color: 'var(--neo-forest)', flexShrink: 0 }} />
                        <Text size="xs" fw={600} className="hl-ellipsis">
                          {kindLabel(e.kind)}
                        </Text>
                      </>
                    )}
                  </Group>
                </Box>
                <ActionIcon size="sm" variant="subtle" color="gray" onClick={() => onRemove(e.id)} aria-label={`Remove ${e.file.name}`}>
                  <IconX size={13} />
                </ActionIcon>
              </Group>
            </Box>
          ))}
        </SimpleGrid>
      )}

      {setAside.length > 0 && (
        <Stack gap={4} mt="sm">
          {setAside.map((a, i) => (
            <Group key={`${a.name}-${i}`} gap={6} wrap="nowrap">
              <IconFileText size={14} style={{ color: 'var(--neo-accent-deep)', flexShrink: 0 }} />
              <Text size="xs">
                <Text span ff="monospace" fw={600}>
                  {a.name}
                </Text>{' '}
                · {a.what}
              </Text>
            </Group>
          ))}
        </Stack>
      )}
    </Paper>
  )
}
