import {
  ActionIcon,
  Alert,
  Badge,
  Box,
  Button,
  Checkbox,
  CopyButton,
  Divider,
  Group,
  Loader,
  NumberInput,
  Paper,
  Radio,
  Select,
  SimpleGrid,
  Stack,
  Stepper,
  Table,
  Text,
  TextInput,
  Tooltip,
} from '@mantine/core'
import { Dropzone } from '@mantine/dropzone'
import { useForm } from '@mantine/form'
import { notifications } from '@mantine/notifications'
import { IconAlertCircle, IconCheck, IconCircleCheck, IconFileUpload, IconX } from '@tabler/icons-react'
import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

import {
  classifyEvidence,
  getModels,
  getTenantSettings,
  submitApplication,
  type ClassifyResponse,
  type PortalCredentials,
  type SubmitResponse,
} from '../../api/client'
import { PageHeader } from '../../components/PageHeader'
import { EvidenceReview } from './EvidenceReview'
import { Section } from './components'

/**
 * Intake form — data entry with the client sitting opposite.
 *
 * ONE scrolling page, submitted once. NOT a wizard: operators jump around and
 * clients correct themselves, so nothing may be lost between steps.
 *
 * The form is **model-driven** (see docs/INTAKE_FORM.md): the operator picks
 * which model arms apply from a vertical checkbox menu ("click all that
 * applicable"). Each selected model pops out a panel with:
 *   - its own file upload (which report to attach), and
 *   - its risk-factor fields.
 *
 * A **face photo** for identification is captured in the Applicant section. It
 * is stored against the applicant and is NEVER a model input. Section 1 is a
 * two-column grid: the face photo on the left, and the client's **name, phone,
 * date of birth and sex** on the right.
 *
 * The **reference** is **generated by the database** (`applicants_ref_seq` →
 * `HL-<seq>` on `applicants.external_ref`), so the operator never types it. The
 * field is read-only; when the backend + DB are connected we fetch a preview
 * (`GET /api/applications/reference`), otherwise it reads "assigned on submit"
 * and the real value comes back in the confirmation.
 *
 * Sections: 1 · Applicant · 2 · Coverage · 3 · Models.
 *
 * Submit is disabled until: name + phone set (1), coverage type/amount set (2),
 * and at least one model selected with its required report attached (3). The
 * identity photo is **not** required — it is biometric data no model reads, so
 * demanding it would collect the most sensitive thing on the form for no gain.
 *
 * Submits multipart to `POST /api/applications`: the applicant, coverage,
 * `models_requested` and the per-model `declared_history` as one JSON field,
 * with each upload paired to the model arm that reads it. The database assigns
 * `external_ref`, and the reference shown in the confirmation is the one it
 * returned — never a client-side guess.
 */

type Scalar = string | boolean | number | string[] | null

interface ModelValues {
  [key: string]: Scalar
}

type SimpleField =
  | { kind: 'checkbox'; key: string; label: string }
  | { kind: 'select'; key: string; label: string; data: string[]; placeholder?: string }
  | { kind: 'number'; key: string; label: string; description?: string }

/**
 * File-type filters, as MIME-type keys with extensions in the value array.
 *
 * The shape matters. react-dropzone validates the **key** as a MIME type and
 * silently drops any entry whose key is not one, warning to the console. Passing
 * an array of bare extensions (`['.dcm', '.png']`) leaves an empty accept object
 * — which disables filtering entirely and accepts every file type.
 *
 * `.dcm` has no registered browser MIME type and most browsers report an empty
 * string for it, so the extension in the value array is what actually matches.
 */
type AcceptMap = Record<string, string[]>

const DICOM: AcceptMap = { 'application/dicom': ['.dcm'] }
const PHOTO: AcceptMap = { 'image/png': ['.png'], 'image/jpeg': ['.jpg', '.jpeg'] }
const DOCUMENT: AcceptMap = { 'application/pdf': ['.pdf'], 'text/plain': ['.txt'] }
const ECG_EXPORT: AcceptMap = { 'text/csv': ['.csv'], 'text/plain': ['.txt', '.tsv'] }

interface ModelDef {
  id: string
  label: string
  modality: string
  upload: { category: string; accept: AcceptMap; instruction: string } | null
  fields: SimpleField[]
}

/**
 * Declared-health options.
 *
 * `key` is what the scoring engine matches on and MUST NOT be edited casually —
 * the authoritative list is SYMPTOM_KEYS and RULES in
 * `apps/api/app/scoring.py`, mirrored in docs/TB.md. A key that does not match
 * fails silently: the rule simply never fires and the applicant is scored on
 * imaging alone. `label` is display text and is safe to reword.
 */
interface Option {
  key: string
  label: string
}

const SYMPTOMS: Option[] = [
  { key: 'cough_over_2_weeks', label: 'Cough lasting more than 2 weeks' },
  { key: 'weight_loss', label: 'Unexplained weight loss' },
  { key: 'night_sweats', label: 'Night sweats' },
  { key: 'haemoptysis', label: 'Coughing up blood' },
  { key: 'fever', label: 'Fever' },
]

const HISTORY_ONCE: Option[] = [
  { key: 'diabetes', label: 'Diabetes' },
  { key: 'hiv', label: 'HIV positive' },
  { key: 'household_tb_contact', label: 'Someone in the household has had TB' },
  { key: 'antibiotics_no_improvement', label: 'Took a course of antibiotics without improvement' },
  { key: 'smoker', label: 'Current or former smoker' },
]

const CARDIO: Option[] = [
  { key: 'hypertension', label: 'Hypertension' },
  { key: 'high_cholesterol', label: 'High cholesterol' },
  { key: 'family_heart_disease', label: 'Family history of heart disease' },
]

// The model registry drives the whole form. Adding or dropping an arm is one
// entry here (see docs/INTAKE_FORM.md and SPEC.md §6).
const MODELS: ModelDef[] = [
  {
    id: 'cxr_lung',
    label: 'Chest X-ray',
    modality: 'TorchXRayVision (DenseNet)',
    upload: {
      category: 'Chest X-ray',
      accept: { ...DICOM, ...PHOTO },
      instruction: 'Chest X-ray — .dcm, .png, or .jpg',
    },
    fields: [],
  },
  {
    id: 'mirai',
    label: 'Mirai',
    modality: 'Breast · mammography',
    upload: {
      category: 'Mammogram',
      accept: DICOM,
      instruction: 'Screening mammogram, all four views (right/left MLO and CC) — four .dcm files',
    },
    fields: [
      { kind: 'checkbox', key: 'family_breast_cancer', label: 'Family history of breast cancer' },
      { kind: 'checkbox', key: 'prior_biopsy', label: 'Prior breast biopsy' },
      {
        kind: 'select',
        key: 'brca_status',
        label: 'Known BRCA / genetic test result',
        data: ['Not tested', 'Negative', 'Positive'],
        placeholder: 'Not tested',
      },
    ],
  },
  {
    id: 'eyepacs',
    label: 'EyePACS',
    modality: 'Retinopathy · fundus',
    upload: {
      category: 'Retinal photo',
      accept: { ...PHOTO, ...DICOM },
      instruction: 'Retinal / fundus photo — .png, .jpg, or .dcm',
    },
    fields: [
      {
        kind: 'select',
        key: 'diabetes_duration',
        label: 'Diabetes duration',
        data: ['No diabetes', 'Under 5 years', '5–10 years', 'Over 10 years'],
        placeholder: 'Select',
      },
      { kind: 'checkbox', key: 'hypertension', label: 'Hypertension' },
      { kind: 'checkbox', key: 'smoker', label: 'Current or former smoker' },
    ],
  },
  {
    id: 'ecg',
    label: '12-lead ECG',
    modality: 'Rhythm · conduction · ECG age',
    upload: {
      category: '12-lead ECG',
      // The signal the machine exports, not a picture of it: a scanned strip
      // holds 2.5 s of each lead at poor fidelity, and the models want ten.
      accept: ECG_EXPORT,
      instruction: 'ECG export with all 12 leads and a time column or sampling rate — .csv or .txt',
    },
    fields: [
      { kind: 'checkbox', key: 'palpitations', label: 'Palpitations or irregular heartbeat' },
      { kind: 'checkbox', key: 'known_arrhythmia', label: 'Known arrhythmia or pacemaker' },
    ],
  },
  {
    id: 'biobert',
    label: 'Clinical notes and prescriptions',
    modality: 'Medication check · disclosure',
    upload: {
      category: 'Clinical note',
      accept: DOCUMENT,
      // A scanned PDF has no text layer and is refused with that reason; the
      // note has to be the exported or typed text.
      instruction: 'Discharge summary, prescription or physician report — .pdf (with text) or .txt',
    },
    fields: [],
  },
  {
    id: 'xgboost',
    label: 'Blood panel and lifestyle',
    modality: 'Mortality · phenotypic age',
    upload: null,
    // The nine blood values are Levine's Phenotypic Age inputs, in the units a
    // Bangladeshi laboratory prints. The keys and units are read by
    // `apps/api/app/arms/mortality.py`; a value typed in the wrong unit is
    // refused there rather than silently scored decades older.
    fields: [
      { kind: 'number', key: 'albumin_g_dl', label: 'Serum albumin (g/dL)', description: 'Liver function test. Typical 3.5–5.0. The nine blood values are optional together: with all nine the phenotypic age is computed as well.' },
      { kind: 'number', key: 'creatinine_mg_dl', label: 'Serum creatinine (mg/dL)', description: 'Typical 0.6–1.2.' },
      { kind: 'number', key: 'glucose_mg_dl', label: 'Glucose (mg/dL)', description: 'Fasting if available. Typical 70–100.' },
      { kind: 'number', key: 'crp_mg_l', label: 'C-reactive protein (mg/L)', description: 'Typical under 3. Enter 0 for "below detection".' },
      { kind: 'number', key: 'lymphocyte_pct', label: 'Lymphocytes (%)', description: 'From the CBC differential. Typical 20–40.' },
      { kind: 'number', key: 'mcv_fl', label: 'Mean cell volume (fL)', description: 'From the CBC. Typical 80–100.' },
      { kind: 'number', key: 'rdw_pct', label: 'Red cell distribution width, RDW-CV (%)', description: 'From the CBC. Typical 11.5–14.5. Not RDW-SD.' },
      { kind: 'number', key: 'alp_u_l', label: 'Alkaline phosphatase (U/L)', description: 'Liver function test. Typical 40–130.' },
      { kind: 'number', key: 'wbc_10e3_ul', label: 'White blood cells (×10³/µL)', description: 'From the CBC. Typical 4–11.' },
      // Optional. These feed the kidney, liver and weight readings shown beside
      // the phenotypic age; they never move the score.
      { kind: 'number', key: 'ast_u_l', label: 'AST (U/L) — optional', description: 'Liver function test. With ALT and platelets gives the FIB-4 fibrosis index.' },
      { kind: 'number', key: 'alt_u_l', label: 'ALT (U/L) — optional' },
      { kind: 'number', key: 'platelets_10e3_ul', label: 'Platelets (×10³/µL) — optional', description: 'From the CBC.' },
      { kind: 'number', key: 'sbp_mmhg', label: 'Systolic blood pressure (mm Hg) — optional', description: 'Seated, at rest.' },
      { kind: 'number', key: 'height_cm', label: 'Height (cm)' },
      { kind: 'number', key: 'weight_kg', label: 'Weight (kg)' },
      { kind: 'select', key: 'alcohol', label: 'Alcohol use', data: ['None', 'Occasionally', 'Regularly'], placeholder: 'Select' },
      { kind: 'select', key: 'activity', label: 'Physical activity', data: ['Sedentary', 'Light', 'Moderate', 'Active'], placeholder: 'Select' },
      { kind: 'select', key: 'occupation', label: 'Occupation', data: ['Office / professional', 'Manual / physical', 'Retired', 'Student', 'Not employed'], placeholder: 'Select' },
      { kind: 'checkbox', key: 'smoker', label: 'Current or former smoker' },
    ],
  },
]

const MAX_FILE_BYTES = 50 * 1024 * 1024
const MAX_FACE_BYTES = 10 * 1024 * 1024

/** The latest date of birth an adult can have: today, eighteen years ago. */
function latestAdultBirthDate(): string {
  const d = new Date()
  d.setFullYear(d.getFullYear() - 18)
  return d.toISOString().slice(0, 10)
}

function isAdult(dob: string): boolean {
  return dob !== '' && dob <= latestAdultBirthDate()
}

interface IntakeForm {
  reference: string
  name: string
  phone: string
  email: string
  dob: string
  sex: string | null
  coverageType: string | null
  coverageAmount: number | null
  policyTerm: string | null
  selectedModels: string[]
  modelFields: Record<string, ModelValues>
}

interface EvidenceFile {
  id: string
  name: string
  size: number
  fileType: string
  // The File itself, not just its name: this is what is uploaded at submit.
  file: File
}

function formatSize(b: number) {
  if (b < 1024) return `${b} B`
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(0)} KB`
  return `${(b / (1024 * 1024)).toFixed(1)} MB`
}

/**
 * Turn the form's per-model state into the `declared_history` shape the API
 * stores and the scoring engine reads (DATABASE.md §C):
 *
 *   { cxr_lung: { symptoms: { cough_over_2_weeks: true, ... },
 *                 history:  { prior_tb: true, ... } } }
 *
 * The form tracks ticked boxes as arrays of keys; the contract is an explicit
 * true/false per option. Sending the array instead would mean every rule reads
 * a missing key as false and never fires.
 */
function declaredHistory(
  selectedModels: string[],
  modelFields: Record<string, ModelValues>,
): Record<string, Record<string, unknown>> {
  const out: Record<string, Record<string, unknown>> = {}

  for (const id of selectedModels) {
    const values = modelFields[id] ?? {}
    const block: Record<string, unknown> = {}

    if (id === 'cxr_lung') {
      const flags = (group: Option[], picked: unknown) =>
        Object.fromEntries(
          group.map((o) => [o.key, ((picked as string[]) ?? []).includes(o.key)]),
        )

      block.symptoms = flags(SYMPTOMS, values.symptoms)
      block.history = {
        ...flags(HISTORY_ONCE, values.history),
        prior_tb: values.prior_tb === true,
        // null (unanswered) is gated at submit, so this is only ever a real answer.
        prior_tb_treatment_completed: values.prior_tb_treatment_completed === 'yes',
      }
      block.cardio = flags(CARDIO, values.cardio)
    } else {
      // Every other arm's fields are already scalars keyed by `key`.
      Object.assign(block, values)
    }

    out[id] = block
  }

  return out
}

function bool(v: Scalar | undefined) {
  return v === true
}

/**
 * The client's portal sign-in, on the confirmation screen.
 *
 * When it was emailed there is nothing to hand over, so only the id is shown.
 * When it was not, this is the one moment the password exists on a screen: the
 * API keeps only its hash and no endpoint can return it again, so the operator
 * gives it to the client who is sitting opposite them.
 */
function PortalSignIn({ portal }: { portal: PortalCredentials }) {
  if (portal.emailed) {
    return (
      <Paper p="md" bd="1px solid var(--mantine-color-default-border)">
        <Text size="sm" fw={600}>Client portal sign-in sent</Text>
        <Text size="sm" c="dimmed" mt={4}>
          Emailed to {portal.email}. Their portal ID is{' '}
          <Text span ff="monospace" fw={600} c="bright">{portal.portalId}</Text>.
        </Text>
      </Paper>
    )
  }

  const rows = [
    { label: 'Portal ID', value: portal.portalId },
    { label: 'Password', value: portal.password ?? '' },
  ]

  return (
    <Paper p="md" bd="1px solid var(--mantine-color-yellow-filled)">
      <Text size="sm" fw={600}>Give the client their portal sign-in now</Text>
      <Text size="sm" c="dimmed" mt={4}>
        {portal.email
          ? `It could not be emailed to ${portal.email}.`
          : 'No email address was given.'}{' '}
        The password is not stored and cannot be shown again after you leave this page.
      </Text>
      <Table mt="sm" withRowBorders={false} verticalSpacing={4}>
        <Table.Tbody>
          {rows.map((row) => (
            <Table.Tr key={row.label}>
              <Table.Td w={90}>
                <Text size="xs" c="dimmed">{row.label}</Text>
              </Table.Td>
              <Table.Td>
                <Text ff="monospace" fw={600}>{row.value}</Text>
              </Table.Td>
              <Table.Td w={80} ta="right">
                <CopyButton value={row.value}>
                  {({ copied, copy }) => (
                    <Button size="compact-xs" variant="light" onClick={copy}>
                      {copied ? 'Copied' : 'Copy'}
                    </Button>
                  )}
                </CopyButton>
              </Table.Td>
            </Table.Tr>
          ))}
        </Table.Tbody>
      </Table>
      <Text size="xs" c="dimmed" mt="sm">
        They sign in from the Client tab on the sign-in page.
      </Text>
    </Paper>
  )
}

export function IntakePage() {
  const form = useForm<IntakeForm>({
    initialValues: {
      reference: '',
      name: '',
      phone: '',
      email: '',
      dob: '',
      sex: null,
      coverageType: null,
      coverageAmount: null,
      policyTerm: null,
      selectedModels: [],
      modelFields: {},
    },
  })

  // Which models actually run is a fact about the backend. The form used to
  // offer all seven as though they worked; only the chest X-ray does, and an
  // operator attaching a mammogram got no score and no explanation.
  // The company's rates, for the cover dropdown. Amounts are multiples of the
  // reference cover, each shown with the standard plan's monthly premium at
  // that amount, so the operator sees the price as they pick.
  const { data: policy } = useQuery({ queryKey: ['tenant-settings'], queryFn: getTenantSettings })
  const coverOptions = (() => {
    const reference = policy?.referenceCoverBdt ?? 1_000_000
    const base = policy?.premiumLowBdt ?? 5_000
    return [0.25, 0.5, 1, 1.5, 2, 3, 5, 10].map((m) => {
      const amount = Math.round((reference * m) / 50_000) * 50_000
      const premium = Math.round(base * (amount / reference))
      return {
        value: String(amount),
        label: `৳${amount.toLocaleString('en-IN')} · from ৳${premium.toLocaleString('en-IN')} a month`,
      }
    })
  })()

  const { data: catalogue = [] } = useQuery({
    queryKey: ['models'],
    queryFn: getModels,
    staleTime: 5 * 60 * 1000,
  })
  const availability = new Map(catalogue.map((m) => [m.id, m]))
  const isAvailable = (id: string) => availability.get(id)?.available ?? false

  const [modelFiles, setModelFiles] = useState<Record<string, EvidenceFile[]>>({})
  const [facePhoto, setFacePhoto] = useState<File | null>(null)
  const [facePreview, setFacePreview] = useState<string | null>(null)
  const [rejectNote, setRejectNote] = useState<Record<string, string | null>>({})
  // The review step between pressing submit and anything being scored.
  // `classified` is null until the API answers; `overrides` holds the
  // operator's corrections, keyed by filename.
  // Which of the four steps is open. The last one is the check of what each
  // file is, which used to be a dialog; as a step it is part of the form.
  const [step, setStep] = useState(0)
  const [classified, setClassified] = useState<ClassifyResponse | null>(null)
  const [overrides, setOverrides] = useState<Record<string, string>>({})

  const [submitting, setSubmitting] = useState(false)
  const [submitted, setSubmitted] = useState<SubmitResponse | null>(null)
  const [submitError, setSubmitError] = useState<string | null>(null)
  const navigate = useNavigate()

  // The reference is GENERATED BY THE DATABASE (applicants_ref_seq -> HL-<seq>)
  // by a trigger at INSERT, so there is nothing to preview and the operator
  // never types it. The real value comes back in the submit response.

  const toggleSet = (modelId: string, key: string, value: string) => {
    form.setFieldValue('modelFields', (current: Record<string, ModelValues>) => {
      const block = (current[modelId]?.[key] as string[]) ?? []
      return {
        ...current,
        [modelId]: {
          ...(current[modelId] ?? {}),
          [key]: block.includes(value) ? block.filter((v) => v !== value) : [...block, value],
        },
      }
    })
  }

  const setField = (modelId: string, key: string, value: Scalar) => {
    form.setFieldValue('modelFields', (current: Record<string, ModelValues>) => ({
      ...current,
      [modelId]: { ...(current[modelId] ?? {}), [key]: value },
    }))
  }

  const toggleModel = (id: string) => {
    // A model that cannot score is not selectable. Letting someone attach a
    // mammogram that will never be read wastes their time and the client's.
    if (!isAvailable(id)) return
    // An updater, not a read-then-write: dropping a folder calls this once per
    // file, and a derived write would use the values captured at render, so
    // every call would undo the one before it and only the last reader would
    // survive — taking its files with it.
    form.setFieldValue('selectedModels', (current: string[]) =>
      current.includes(id) ? current.filter((m) => m !== id) : [...current, id],
    )
  }

  const selected = MODELS.filter((m) => form.values.selectedModels.includes(m.id))

  const addModelFiles = (
    modelId: string,
    dropped: File[],
    fileType: string,
    alreadyClassified = false,
  ) => {
    setRejectNote((p) => ({ ...p, [modelId]: null }))
    const added: EvidenceFile[] = dropped.map((f) => ({
      id: crypto.randomUUID(),
      name: f.name,
      size: f.size,
      fileType,
      file: f,
    }))
    setModelFiles((prev) => ({ ...prev, [modelId]: [...(prev[modelId] ?? []), ...added] }))

    // Classify as the file lands rather than at submit. By the time the
    // operator finishes the form the answer is already cached, so the review
    // screen opens instantly instead of making them wait with a client
    // watching. A failure here is silent: submit re-classifies anyway, and an
    // error about a background request would mean nothing to the operator.
    if (alreadyClassified) return
    void classifyEvidence(dropped)
      .then((result) => {
        setClassified((prev) =>
          prev ? { ...prev, files: [...prev.files, ...result.files] } : result,
        )
      })
      .catch(() => {})
  }

  /**
   * The one place to drop everything. The platform says what each file is and
   * which reader takes it; files land in that reader's panel, and the reader
   * is switched on. What nothing reads yet is listed, with the reason, and is
   * not attached: a file that goes nowhere should say so, not vanish.
   */
  const [identifying, setIdentifying] = useState(false)
  const [identified, setIdentified] = useState<
    { name: string; kind: string; reader: string | null; reason: string }[]
  >([])

  /**
   * A dropped folder can carry two JSON files the readers never see:
   * `client.json` fills in the client and the cover, `blood-panel.json` fills
   * in the lab reader's values. Everything else goes to the API to be
   * identified.
   */
  const takeJson = async (files: File[]): Promise<File[]> => {
    const rest: File[] = []
    const alreadyOn = new Set(form.values.selectedModels)
    for (const file of files) {
      if (!file.name.toLowerCase().endsWith('.json')) {
        rest.push(file)
        continue
      }
      try {
        const data = JSON.parse(await file.text()) as Record<string, unknown>
        if (typeof data.name === 'string' || typeof data.phone === 'string') {
          const cover = (data.coverage ?? {}) as Record<string, unknown>
          form.setValues({
            name: typeof data.name === 'string' ? data.name : form.values.name,
            phone: typeof data.phone === 'string' ? data.phone : form.values.phone,
            email: typeof data.email === 'string' ? data.email : form.values.email,
            dob: typeof data.dateOfBirth === 'string' ? data.dateOfBirth : form.values.dob,
            sex: typeof data.sex === 'string' ? data.sex : form.values.sex,
            coverageType: typeof cover.type === 'string' ? cover.type : form.values.coverageType,
            coverageAmount: typeof cover.amount === 'number' ? cover.amount : form.values.coverageAmount,
            policyTerm: typeof cover.term === 'string' ? cover.term : form.values.policyTerm,
          })
          const questions = (data.questions ?? {}) as Record<string, Record<string, Scalar>>
          for (const [modelId, values] of Object.entries(questions)) {
            if (!isAvailable(modelId)) continue
            if (!alreadyOn.has(modelId)) {
              alreadyOn.add(modelId)
              toggleModel(modelId)
            }
            setFields(modelId, values)
          }
          setIdentified((prev) => [
            ...prev,
            { name: file.name, kind: 'Client details', reader: null, reason: 'Filled in the client and the cover' },
          ])
        } else if ('albumin_g_dl' in data || 'creatinine_mg_dl' in data) {
          if (isAvailable('xgboost')) {
            if (!alreadyOn.has('xgboost')) {
              alreadyOn.add('xgboost')
              toggleModel('xgboost')
            }
            setFields('xgboost', data as Record<string, Scalar>)
            setIdentified((prev) => [
              ...prev,
              { name: file.name, kind: 'Blood panel', reader: availability.get('xgboost')?.label ?? 'Blood panel', reason: 'Values typed in for you' },
            ])
          }
        } else {
          rest.push(file)
        }
      } catch {
        rest.push(file)
      }
    }
    return rest
  }

  /** Several values for one reader at once (setField one at a time would lose all but the last). */
  const setFields = (modelId: string, values: Record<string, Scalar>) => {
    form.setFieldValue('modelFields', (current: Record<string, ModelValues>) => ({
      ...current,
      [modelId]: { ...(current[modelId] ?? {}), ...values },
    }))
  }

  const dropEverything = async (all: File[]) => {
    setIdentifying(true)
    try {
      const dropped = await takeJson(all)
      if (dropped.length === 0) return
      const result = await classifyEvidence(dropped)
      setClassified((prev) =>
        prev
          ? { files: [...prev.files, ...result.files], choices: result.choices }
          : result,
      )
      const byName = new Map(dropped.map((f) => [f.name, f]))
      const rows: typeof identified = []
      const woken = new Set(form.values.selectedModels)
      for (const found of result.files) {
        const file = byName.get(found.filename)
        const choice = (result.choices ?? []).find((c) => c.kind === found.kind)
        const readerId = (choice?.arms ?? []).find((arm) => isAvailable(arm)) ?? null
        const reader = MODELS.find((m) => m.id === readerId)
        if (file && reader && reader.upload) {
          // `toggleModel` is idempotent through its updater, but a second call
          // for the same reader would turn it back off, so the set is tracked
          // here across the whole drop rather than read back from the form.
          if (!woken.has(reader.id)) {
            woken.add(reader.id)
            toggleModel(reader.id)
          }
          addModelFiles(reader.id, [file], reader.upload.category, true)
        }
        rows.push({
          name: found.filename,
          kind: choice?.label ?? found.kind,
          reader: reader ? (availability.get(reader.id)?.label ?? reader.label) : null,
          reason: found.reason,
        })
      }
      setIdentified((prev) => [...prev, ...rows])
    } catch (err) {
      notifications.show({
        title: 'Could not identify the files',
        message: err instanceof Error ? err.message : 'Try dropping them into a reader directly.',
        color: 'red',
      })
    } finally {
      setIdentifying(false)
    }
  }

  const addModelReject = (modelId: string, rejects: { file: File }[]) => {
    const tooBig = rejects.some((r) => r.file.size > MAX_FILE_BYTES)
    setRejectNote((p) => ({
      ...p,
      [modelId]: tooBig
        ? 'File rejected — the 50 MB limit was exceeded.'
        : 'File rejected — check the accepted type for this model.',
    }))
  }

  const removeModelFile = (modelId: string, id: string) => {
    const gone = (modelFiles[modelId] ?? []).find((f) => f.id === id)
    setModelFiles((prev) => ({
      ...prev,
      [modelId]: (prev[modelId] ?? []).filter((f) => f.id !== id),
    }))
    // Drop its classification as well. A row left behind for a file that is no
    // longer attached would sit unresolved and block submit forever.
    if (gone) {
      setClassified((prev) =>
        prev ? { ...prev, files: prev.files.filter((f) => f.filename !== gone.name) } : prev,
      )
      setOverrides((prev) => {
        const { [gone.name]: _removed, ...rest } = prev
        return rest
      })
    }
  }

  const setFace = (file: File | null) => {
    if (facePreview) URL.revokeObjectURL(facePreview)
    setFacePhoto(file)
    setFacePreview(file ? URL.createObjectURL(file) : null)
  }

  const addFacePhoto = (dropped: File[]) => {
    setRejectNote((p) => ({ ...p, face: null }))
    if (dropped.length === 0) return
    setFace(dropped[0])
  }

  const addFaceReject = (rejects: { file: File }[]) => {
    const tooBig = rejects.some((r) => r.file.size > MAX_FACE_BYTES)
    setRejectNote((p) => ({
      ...p,
      face: tooBig
        ? 'Face photo rejected — the 10 MB limit was exceeded.'
        : 'Face photo rejected — use a .png or .jpg image.',
    }))
  }

  const modelHasUpload = (m: ModelDef) => (modelFiles[m.id] ?? []).length > 0

  /**
   * "Previously treated for TB" ticked but the follow-up left blank would be
   * sent as null and read downstream as "did not complete" — silently scoring
   * the applicant 25 points higher than an answered "yes" would. Require it.
   */
  const tbFollowUpAnswered = (() => {
    if (!form.values.selectedModels.includes('cxr_lung')) return true
    const values = form.values.modelFields.cxr_lung
    if (!bool(values?.prior_tb)) return true
    return (
      values?.prior_tb_treatment_completed === 'yes' ||
      values?.prior_tb_treatment_completed === 'no'
    )
  })()

  const modelsSectionComplete =
    selected.length > 0 &&
    selected.every((m) => m.upload === null || modelHasUpload(m)) &&
    tbFollowUpAnswered

  const sections = [
    // The identity photo is deliberately not required. It is biometric data
    // that no model reads, so demanding it would collect the most sensitive
    // thing on the form for no benefit (SPEC §9, PII minimisation).
    Boolean(form.values.name.trim()) &&
      Boolean(form.values.phone.trim()) &&
      (form.values.dob === '' || isAdult(form.values.dob)),
    Boolean(form.values.coverageType) && (form.values.coverageAmount ?? 0) > 0,
    modelsSectionComplete,
  ]

  const canSubmit = sections[0] && sections[1] && modelsSectionComplete

  /** Every attached file, paired with the model panel it came from. */
  const uploads = selected.flatMap((m) =>
    (modelFiles[m.id] ?? []).map((f) => ({ file: f.file, arm: m.id })),
  )

  /**
   * Submit opens the review step rather than sending. Nothing is scored until
   * the operator has confirmed what each document is, because a model given the
   * wrong kind of file answers confidently instead of failing.
   */
  const handleSubmit = async () => {
    if (!canSubmit) return
    setSubmitError(null)
    setStep(3)

    // Normally already done as the files landed. This covers the case where
    // that background request failed or is still in flight.
    if (!classified || classified.files.length !== uploads.length) {
      try {
        setClassified(await classifyEvidence(uploads.map((u) => u.file)))
      } catch {
        setClassified({ files: [], choices: [] })
      }
    }
  }

  /** Called from the review step, once every file has a confirmed kind. */
  const sendApplication = async () => {
    setSubmitting(true)
    setSubmitError(null)

    const kindFor = (file: File) => {
      const proposed = classified?.files.find((f) => f.filename === file.name)
      return overrides[file.name] ?? proposed?.kind ?? 'unknown'
    }

    try {
      const result = await submitApplication({
        payload: {
          applicant: {
            name: form.values.name.trim(),
            phone: form.values.phone.trim(),
            dateOfBirth: form.values.dob || null,
            sex: form.values.sex,
            email: form.values.email.trim() || null,
          },
          coverage: {
            coverageType: form.values.coverageType,
            coverageAmount: form.values.coverageAmount,
            policyTerm: form.values.policyTerm,
          },
          modelsRequested: form.values.selectedModels,
          declaredHistory: declaredHistory(form.values.selectedModels, form.values.modelFields),
        },
        files: uploads.map((u) => ({ ...u, kind: kindFor(u.file) })),
        facePhoto: facePhoto,
      })
      setSubmitted(result)
    } catch (err) {
      // Keep the form exactly as it was. The operator has a client sitting
      // opposite and must not have to re-enter anything to retry.
      setSubmitError(err instanceof Error ? err.message : 'The application could not be submitted.')
    } finally {
      setSubmitting(false)
    }
  }

  const dropEverythingZone = (
    <>
            <Dropzone
              onDrop={(files) => void dropEverything(files)}
              onReject={(rejects) =>
                notifications.show({
                  title: `${rejects.length} file${rejects.length === 1 ? '' : 's'} not accepted`,
                  message: 'Images, DICOM, ECG exports (.csv), PDF and text up to 50 MB.',
                  color: 'red',
                })
              }
              accept={{ ...DICOM, ...PHOTO, ...DOCUMENT, ...ECG_EXPORT, 'application/json': ['.json'] }}
              maxSize={MAX_FILE_BYTES}
              loading={identifying}
              multiple
              className="drop-all"
            >
              <Group justify="center" gap="md" style={{ pointerEvents: 'none' }} py="md">
                <IconFileUpload size={30} stroke={1.4} style={{ color: 'var(--neo-accent)' }} />
                <div>
                  <Text size="sm" fw={600}>
                    Drop every file the client brought here
                  </Text>
                  <Text size="xs" style={{ color: 'var(--neo-muted)' }}>
                    Scans, retinal photos, ECG exports, reports. The platform works out what each
                    file is and which reader takes it, and switches that reader on below.
                  </Text>
                </div>
              </Group>
            </Dropzone>

            {identified.length > 0 && (
              <Table fz="xs" withRowBorders={false} verticalSpacing={4} className="identified">
                <Table.Thead>
                  <Table.Tr>
                    <Table.Th>File</Table.Th>
                    <Table.Th>Identified as</Table.Th>
                    <Table.Th>Read by</Table.Th>
                  </Table.Tr>
                </Table.Thead>
                <Table.Tbody>
                  {identified.map((row, i) => (
                    <Table.Tr key={`${row.name}-${i}`} className="identified__row">
                      <Table.Td ff="monospace">{row.name}</Table.Td>
                      <Table.Td>
                        {row.kind}
                        <Text span size="xs" ml={6} style={{ color: 'var(--neo-muted)' }}>
                          {row.reason}
                        </Text>
                      </Table.Td>
                      <Table.Td>
                        {row.reader ? (
                          <Badge size="xs" color="teal" variant="light">
                            {row.reader}
                          </Badge>
                        ) : (
                          <Badge size="xs" color="gray" variant="outline">
                            No reader yet. Not attached.
                          </Badge>
                        )}
                      </Table.Td>
                    </Table.Tr>
                  ))}
                </Table.Tbody>
              </Table>
            )}
    </>
  )

  if (submitted) {
    return (
      <Stack gap="md" maw={560}>
        <Alert icon={<IconCircleCheck size={18} />} color="teal" title="Application submitted">
          <Text size="sm">
            Reference <Text span ff="monospace" fw={600}>{submitted.reference}</Text>{' '}
            is in the queue. The models are reading the evidence now — the queue
            updates on its own when the result lands.
          </Text>
        </Alert>
        {submitted.portal && <PortalSignIn portal={submitted.portal} />}
        <Group>
          <Button size="xs" onClick={() => navigate('/queue')}>
            Back to queue
          </Button>
          <Button
            size="xs"
            variant="light"
            onClick={() => navigate(`/applications/${submitted.id}`)}
          >
            Open this application
          </Button>
        </Group>
      </Stack>
    )
  }

  return (
    <Stack gap="lg" maw={980}>
      <PageHeader screen="intake" />

      <Stepper
        active={step}
        onStepClick={setStep}
        allowNextStepsSelect={false}
        size="sm"
        completedIcon={<IconCheck size={16} />}
      >
        <Stepper.Step label="Client" description="Who is applying" allowStepSelect={step > 0}>
          <div key="client" className="page-enter">
            <Text size="sm" mt="md" mb="xs" style={{ color: 'var(--neo-muted)' }}>
              Have the client's folder? Drop everything in it here: the client's details, their cover
              and every file are taken care of, and each reader is switched on.
            </Text>
            {dropEverythingZone}
      {/* ── Section 1 · Applicant ─────────────────────────────── */}
      <Section n="1" title="Applicant" complete={sections[0]}>
        <TextInput
          label="Reference"
          description="Generated by the database (HL-&lt;seq&gt;) when the application is saved. Read-only."
          readOnly
          disabled
          placeholder="assigned on submit"
          value=""
        />

        <SimpleGrid cols={{ base: 1, md: 2 }} spacing="lg" mt="md">
          <Stack gap="sm">
            <Group grow align="flex-start">
              <TextInput label="Name" required placeholder="Client name" {...form.getInputProps('name')} />
              <TextInput label="Phone" required placeholder="+880 1XXXXXXXXX" {...form.getInputProps('phone')} />
            </Group>
            <TextInput
              label="Email"
              type="email"
              placeholder="client@example.com"
              description="Optional. Their portal sign-in is sent here. Without it, you are shown the sign-in to hand over."
              {...form.getInputProps('email')}
            />
            <Group grow align="flex-start">
              <TextInput
                label="Date of birth"
                type="date"
                description="The client must be 18 or over"
                max={latestAdultBirthDate()}
                min="1900-01-01"
                {...form.getInputProps('dob')}
                error={form.values.dob && !isAdult(form.values.dob) ? 'The client must be at least 18' : undefined}
              />
              <Select
                label="Sex"
                placeholder="Prefer not to say"
                data={['Female', 'Male', 'Other', 'Prefer not to say']}
                clearable
                {...form.getInputProps('sex')}
              />
            </Group>
          </Stack>

          <FacePhotoUpload
            file={facePhoto}
            preview={facePreview}
            note={rejectNote.face}
            onDrop={addFacePhoto}
            onReject={addFaceReject}
            onRemove={() => setFace(null)}
          />
        </SimpleGrid>
      </Section>

      <Divider my="xs" />

          </div>
        </Stepper.Step>

        <Stepper.Step label="Cover" description="What they are asking for" allowStepSelect={step > 1}>
          <div key="cover" className="page-enter">
      {/* ── Section 2 · Coverage requested ─────────────────────── */}
      <Section n="2" title="Coverage requested" complete={sections[1]}>
        <Group align="flex-end">
          <Select
            label="Coverage type"
            placeholder="Select"
            required
            data={['Life', 'Health', 'Critical illness']}
            {...form.getInputProps('coverageType')}
          />
          <Select
            label="Coverage amount (BDT)"
            description="What each amount costs a month on the standard plan, under your company's rates"
            placeholder="Choose an amount"
            required
            searchable
            w={340}
            data={coverOptions}
            value={form.values.coverageAmount != null ? String(form.values.coverageAmount) : null}
            onChange={(v) => form.setFieldValue('coverageAmount', v ? Number(v) : null)}
          />
          <Select
            label="Policy term"
            placeholder="Years"
            data={['1', '5', '10', '20']}
            clearable
            {...form.getInputProps('policyTerm')}
          />
        </Group>
      </Section>

      <Divider my="xs" />

          </div>
        </Stepper.Step>

        <Stepper.Step label="Evidence" description="What to screen, and with what" allowStepSelect={step > 2}>
          <div key="evidence" className="page-enter">
      {/* ── Section 3 · Models ─────────────────────────────────── */}
      <Section n="3" title="Models" complete={sections[2]}>
        {dropEverythingZone}

        {/* No reader picker. The dropped files decide which readers run; the
            only reader that needs asking for is the one that takes typed
            values and no file, and it has its own button below. */}
        <Group justify="space-between" align="center">
          <Text size="sm" c="dimmed">
            {selected.length === 0
              ? 'Drop the files above and the readers appear here.'
              : `${selected.length} reader${selected.length === 1 ? '' : 's'} will run on this application.`}
          </Text>
          {!form.values.selectedModels.includes('xgboost') && isAvailable('xgboost') && (
            <Button size="xs" variant="light" onClick={() => toggleModel('xgboost')}>
              Add blood panel and lifestyle
            </Button>
          )}
        </Group>

        <Stack gap="md">
          {selected.map((m) => (
              <Paper key={m.id} bd="1px solid var(--mantine-color-default-border)" p="md">
                <Group justify="space-between" align="flex-start" mb={4}>
                  <Text fw={600} size="sm">
                    {availability.get(m.id)?.label ?? m.label}
                    <Text span c="dimmed" fw={400}>
                      {' '}
                      · screens for {availability.get(m.id)?.screensFor ?? m.modality}
                    </Text>
                  </Text>
                  <Group gap="xs" wrap="nowrap">
                    <Badge size="xs" color="teal" variant="light">
                      {availability.get(m.id)?.armVersion ?? 'ready'}
                    </Badge>
                    <Tooltip label="Do not run this reader on this application" withArrow>
                      <ActionIcon
                        size="sm"
                        variant="subtle"
                        aria-label={`Remove ${m.label}`}
                        onClick={() => toggleModel(m.id)}
                      >
                        <IconX size={14} />
                      </ActionIcon>
                    </Tooltip>
                  </Group>
                </Group>
                {/* The caveat travels with the model, not a document. */}
                {availability.get(m.id)?.validation && (
                  <Text size="xs" c="yellow.7" mb="sm">
                    {availability.get(m.id)?.validation}
                  </Text>
                )}

                {m.upload ? (
                  <PanelUpload
                    model={m}
                    files={modelFiles[m.id] ?? []}
                    note={rejectNote[m.id]}
                    onDrop={(files) => addModelFiles(m.id, files, m.upload!.category)}
                    onReject={(rejects) => addModelReject(m.id, rejects)}
                    onRemove={(id) => removeModelFile(m.id, id)}
                  />
                ) : (
                  <Alert color="gray" variant="light" mb="md">
                    <Text size="sm">No report needed — complete the demographic form.</Text>
                  </Alert>
                )}

                <ModelFieldControls
                  model={m}
                  values={form.values.modelFields[m.id] ?? {}}
                  setField={setField}
                  toggleSet={toggleSet}
                />
              </Paper>
          ))}
        </Stack>
      </Section>

          </div>
        </Stepper.Step>

        <Stepper.Step label="Check" description="Confirm what each file is">
          <div key="check" className="page-enter">
            <Paper p="md" bd="1px solid var(--neo-border-mid)" mt="md">
              <EvidenceReview
                inline
                opened
                readerNames={Object.fromEntries(catalogue.map((m) => [m.id, m.label]))}
                result={classified}
                overrides={overrides}
                onOverride={(filename, kind) =>
                  setOverrides((prev) => ({ ...prev, [filename]: kind }))
                }
                onConfirm={() => void sendApplication()}
                onCancel={() => setStep(2)}
                submitting={submitting}
              />
            </Paper>
          </div>
        </Stepper.Step>
      </Stepper>

      {/*
        A failed submit must never clear the form: the operator has a client in
        front of them, and re-entering everything is the difference between a
        retry and a lost appointment.
      */}
      {submitError && (
        <Alert
          color="red"
          variant="light"
          icon={<IconAlertCircle size={16} />}
          title="The application was not submitted"
        >
          <Text size="sm">{submitError}</Text>
          <Text size="xs" c="dimmed" mt={4}>
            Nothing has been lost. Everything you entered is still here. Try again.
          </Text>
        </Alert>
      )}

      {/* The last step carries its own buttons. */}
      {step < 3 && (
        <Group justify="space-between" align="center">
          <Button variant="subtle" size="sm" disabled={step === 0} onClick={() => setStep(step - 1)}>
            Back
          </Button>
          <Group gap="sm" align="center">
            <Text size="xs" c="dimmed" ta="right" maw={420}>
              {step === 0 && 'A name and a phone number are needed. Everything else here is optional.'}
              {step === 1 && 'The cover type and amount decide which plan is offered.'}
              {step === 2 &&
                'At least one model with its report attached. Next you confirm what each file is; nothing is scored until then.'}
            </Text>
            {step < 2 ? (
              <Button size="sm" disabled={!sections[step]} onClick={() => setStep(step + 1)}>
                Continue
              </Button>
            ) : (
              <Button size="sm" disabled={!canSubmit} onClick={handleSubmit}>
                Check the files
              </Button>
            )}
          </Group>
        </Group>
      )}

      {submitting && (
        <Group gap="xs" c="dimmed">
          <Loader size={14} />
          <Text size="xs">Uploading evidence and creating the application…</Text>
        </Group>
      )}
    </Stack>
  )
}

function FacePhotoUpload({
  file,
  preview,
  note,
  onDrop,
  onReject,
  onRemove,
}: {
  file: File | null
  preview: string | null
  note: string | null
  onDrop: (files: File[]) => void
  onReject: (rejects: { file: File }[]) => void
  onRemove: () => void
}) {
  return (
    <Paper bd="1px solid var(--mantine-color-default-border)" p="md" mt="md">
      <Group gap="xs" mb={4}>
        <Text fw={600} size="sm">
          Identity photo
        </Text>
        <Badge size="xs" color="gray" variant="outline">
          Optional
        </Badge>
      </Group>
      <Text size="xs" c="dimmed" mb="sm">
        For your own records only. No model reads it, and it is never shown next
        to the risk score — a face beside a score can only bias the decision.
        Skip it if you do not need it.
      </Text>

      {file && preview ? (
        <Group align="flex-start" gap="md">
          <Box
            w={96}
            h={96}
            style={{
              borderRadius: 6,
              overflow: 'hidden',
              border: '1px solid var(--mantine-color-default-border)',
              flexShrink: 0,
            }}
          >
            <img
              src={preview}
              alt="Face photo preview"
              style={{ width: '100%', height: '100%', objectFit: 'cover' }}
            />
          </Box>
          <Stack gap={4} align="flex-start">
            <Text ff="monospace" size="sm">
              {file.name}
            </Text>
            <Text size="xs" c="dimmed">
              {formatSize(file.size)}
            </Text>
            <Button size="xs" variant="subtle" color="red" onClick={onRemove}>
              Remove
            </Button>
          </Stack>
        </Group>
      ) : (
        <Dropzone
          accept={PHOTO}
          maxSize={MAX_FACE_BYTES}
          multiple={false}
          onDrop={onDrop}
          onReject={onReject}
        >
          <Group justify="center" py="md" style={{ pointerEvents: 'none' }}>
            <Text size="sm" c="dimmed">
              Drop the client’s face photo here, or click to browse — .png or
              .jpg, max 10 MB.
            </Text>
          </Group>
        </Dropzone>
      )}

      {note && (
        <Alert color="red" variant="light" icon={<IconAlertCircle size={16} />} mt="sm">
          <Text size="sm">{note}</Text>
        </Alert>
      )}
    </Paper>
  )
}

function PanelUpload({
  model,
  files,
  note,
  onDrop,
  onReject,
  onRemove,
}: {
  model: ModelDef
  files: EvidenceFile[]
  note: string | null
  onDrop: (files: File[]) => void
  onReject: (rejects: { file: File }[]) => void
  onRemove: (id: string) => void
}) {
  const upload = model.upload!
  return (
    <Box mb="md">
      <Alert icon={<IconFileUpload size={16} />} color="clinical" variant="light" mb="sm">
        <Text size="sm">
          Please submit: <Text span fw={600}>{upload.instruction}</Text>
        </Text>
      </Alert>

      <Dropzone
        accept={upload.accept}
        maxSize={MAX_FILE_BYTES}
        multiple
        onDrop={onDrop}
        onReject={onReject}
      >
        <Group justify="center" gap="xl" py="sm" style={{ pointerEvents: 'none' }}>
          <Dropzone.Accept>
            <IconFileUpload size={24} color="var(--mantine-color-clinical-3)" />
          </Dropzone.Accept>
          <Dropzone.Reject>
            <IconAlertCircle size={24} color="var(--mantine-color-red-5)" />
          </Dropzone.Reject>
          <Dropzone.Idle>
            <IconFileUpload size={24} color="var(--mantine-color-dimmed)" />
          </Dropzone.Idle>
          <Stack gap={2} align="center">
            <Text fw={500} size="sm">
              Drop files here or click to browse
            </Text>
            <Text size="xs" c="dimmed">
              {upload.instruction} · max 50 MB per file
            </Text>
          </Stack>
        </Group>
      </Dropzone>

      {note && (
        <Alert color="red" variant="light" icon={<IconAlertCircle size={16} />} mt="sm">
          <Text size="sm">{note}</Text>
        </Alert>
      )}

      {files.length > 0 && (
        <Table mt="sm">
          <Table.Thead>
            <Table.Tr>
              <Table.Th>File</Table.Th>
              <Table.Th>Size</Table.Th>
              <Table.Th w={60} />
            </Table.Tr>
          </Table.Thead>
          <Table.Tbody>
            {files.map((f) => (
              <Table.Tr key={f.id}>
                <Table.Td ff="monospace">{f.name}</Table.Td>
                <Table.Td>{formatSize(f.size)}</Table.Td>
                <Table.Td>
                  <ActionIcon
                    size="sm"
                    variant="subtle"
                    color="red"
                    aria-label="Remove file"
                    onClick={() => onRemove(f.id)}
                  >
                    <IconX size={14} />
                  </ActionIcon>
                </Table.Td>
              </Table.Tr>
            ))}
          </Table.Tbody>
        </Table>
      )}
    </Box>
  )
}

function ModelFieldControls({
  model,
  values,
  setField,
  toggleSet,
}: {
  model: ModelDef
  values: ModelValues
  setField: (modelId: string, key: string, value: Scalar) => void
  toggleSet: (modelId: string, key: string, value: string) => void
}) {
  if (model.id === 'cxr_lung') {
    return (
      <CxrPanel values={values} setField={setField} toggleSet={toggleSet} />
    )
  }

  if (model.fields.length === 0) {
    return (
      <Text size="xs" c="dimmed">
        No additional questions — the {model.label} model reads the uploaded report directly.
      </Text>
    )
  }

  return (
    <Stack gap="sm">
      {model.fields.map((f) => {
        if (f.kind === 'checkbox') {
          return (
            <Checkbox
              key={f.key}
              label={f.label}
              checked={bool(values[f.key])}
              onChange={(e) => setField(model.id, f.key, e.currentTarget.checked)}
            />
          )
        }
        if (f.kind === 'select') {
          return (
            <Select
              key={f.key}
              label={f.label}
              placeholder={f.placeholder ?? 'Select'}
              data={f.data}
              clearable
              value={typeof values[f.key] === 'string' ? (values[f.key] as string) : null}
              onChange={(v) => setField(model.id, f.key, v)}
            />
          )
        }
        return (
          <NumberInput
            key={f.key}
            label={f.label}
            description={f.description}
            min={0}
            value={typeof values[f.key] === 'number' ? (values[f.key] as number) : undefined}
            onChange={(v) => setField(model.id, f.key, v === '' ? null : v)}
          />
        )
      })}
    </Stack>
  )
}

function CxrPanel({
  values,
  setField,
  toggleSet,
}: {
  values: ModelValues
  setField: (modelId: string, key: string, value: Scalar) => void
  toggleSet: (modelId: string, key: string, value: string) => void
}) {
  const modelId = 'cxr_lung'
  const sym = (values.symptoms as string[]) ?? []
  const hist = (values.history as string[]) ?? []
  const cardio = (values.cardio as string[]) ?? []

  return (
    <Stack gap="md">
      {/* Current symptoms */}
      <Box>
        <Text fw={600} size="sm" mb="xs">
          Current symptoms
        </Text>
        <Stack gap="xs">
          {SYMPTOMS.map((s) => (
            <Checkbox
              key={s.key}
              label={s.label}
              checked={sym.includes(s.key)}
              onChange={() => toggleSet(modelId, 'symptoms', s.key)}
            />
          ))}
        </Stack>
      </Box>

      {/* TB history */}
      <Box>
        <Text fw={600} size="sm" mb="xs">
          Medical history
        </Text>
        <Stack gap="xs">
          <Checkbox
            label="Previously treated for TB"
            checked={bool(values.prior_tb)}
            onChange={(e) => {
              setField(modelId, 'prior_tb', e.currentTarget.checked)
              // Clear the follow-up when the parent is un-ticked, so a stale
              // answer cannot be submitted for someone with no TB history.
              if (!e.currentTarget.checked) {
                setField(modelId, 'prior_tb_treatment_completed', null)
              }
            }}
          />
          {bool(values.prior_tb) && (
            <Box pl="lg">
              {/*
                Yes/No rather than a checkbox. An unticked box cannot say whether
                the course was not completed or the question was never asked, and
                the two mean different things: a completed course lowers the score
                by 25, an incomplete one does not. Unanswered is sent as null and
                gated at submit rather than guessed.
              */}
              <Radio.Group
                label="Completed the full course of treatment"
                value={(values.prior_tb_treatment_completed as string) ?? ''}
                onChange={(v) => setField(modelId, 'prior_tb_treatment_completed', v)}
              >
                <Group gap="lg" mt={6}>
                  <Radio value="yes" label="Yes" />
                  <Radio value="no" label="No" />
                </Group>
              </Radio.Group>
            </Box>
          )}
          {HISTORY_ONCE.map((h) => (
            <Checkbox
              key={h.key}
              label={h.label}
              checked={hist.includes(h.key)}
              onChange={() => toggleSet(modelId, 'history', h.key)}
            />
          ))}
        </Stack>
      </Box>

      {/* Cardio */}
      <Box>
        <Text fw={600} size="sm" mb="xs">
          Cardiovascular
        </Text>
        <Stack gap="xs">
          {CARDIO.map((c) => (
            <Checkbox
              key={c.key}
              label={c.label}
              checked={cardio.includes(c.key)}
              onChange={() => toggleSet(modelId, 'cardio', c.key)}
            />
          ))}
        </Stack>
      </Box>
    </Stack>
  )
}
