import {
  ActionIcon,
  Alert,
  Badge,
  Box,
  Button,
  Checkbox,
  CopyButton,
  Divider,
  Group,
  Loader,
  NumberInput,
  Paper,
  Radio,
  Select,
  SimpleGrid,
  Stack,
  Table,
  Text,
  TextInput,
} from '@mantine/core'
import { Dropzone } from '@mantine/dropzone'
import { useForm } from '@mantine/form'
import { IconAlertCircle, IconCircleCheck, IconFileUpload, IconX } from '@tabler/icons-react'
import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

import {
  classifyEvidence,
  getModels,
  submitApplication,
  type ClassifyResponse,
  type PortalCredentials,
  type SubmitResponse,
} from '../../api/client'
import { EvidenceReview } from './EvidenceReview'
import { Section } from './components'

/**
 * Intake form — data entry with the client sitting opposite.
 *
 * ONE scrolling page, submitted once. NOT a wizard: operators jump around and
 * clients correct themselves, so nothing may be lost between steps.
 *
 * The form is **model-driven** (see docs/INTAKE_FORM.md): the operator picks
 * which model arms apply from a vertical checkbox menu ("click all that
 * applicable"). Each selected model pops out a panel with:
 *   - its own file upload (which report to attach), and
 *   - its risk-factor fields.
 *
 * A **face photo** for identification is captured in the Applicant section. It
 * is stored against the applicant and is NEVER a model input. Section 1 is a
 * two-column grid: the face photo on the left, and the client's **name, phone,
 * date of birth and sex** on the right.
 *
 * The **reference** is **generated by the database** (`applicants_ref_seq` →
 * `HL-<seq>` on `applicants.external_ref`), so the operator never types it. The
 * field is read-only; when the backend + DB are connected we fetch a preview
 * (`GET /api/applications/reference`), otherwise it reads "assigned on submit"
 * and the real value comes back in the confirmation.
 *
 * Sections: 1 · Applicant · 2 · Coverage · 3 · Models.
 *
 * Submit is disabled until: name + phone set (1), coverage type/amount set (2),
 * and at least one model selected with its required report attached (3). The
 * identity photo is **not** required — it is biometric data no model reads, so
 * demanding it would collect the most sensitive thing on the form for no gain.
 *
 * Submits multipart to `POST /api/applications`: the applicant, coverage,
 * `models_requested` and the per-model `declared_history` as one JSON field,
 * with each upload paired to the model arm that reads it. The database assigns
 * `external_ref`, and the reference shown in the confirmation is the one it
 * returned — never a client-side guess.
 */

type Scalar = string | boolean | number | string[] | null

interface ModelValues {
  [key: string]: Scalar
}

type SimpleField =
  | { kind: 'checkbox'; key: string; label: string }
  | { kind: 'select'; key: string; label: string; data: string[]; placeholder?: string }
  | { kind: 'number'; key: string; label: string; description?: string }

/**
 * File-type filters, as MIME-type keys with extensions in the value array.
 *
 * The shape matters. react-dropzone validates the **key** as a MIME type and
 * silently drops any entry whose key is not one, warning to the console. Passing
 * an array of bare extensions (`['.dcm', '.png']`) leaves an empty accept object
 * — which disables filtering entirely and accepts every file type.
 *
 * `.dcm` has no registered browser MIME type and most browsers report an empty
 * string for it, so the extension in the value array is what actually matches.
 */
type AcceptMap = Record<string, string[]>

const DICOM: AcceptMap = { 'application/dicom': ['.dcm'] }
const PHOTO: AcceptMap = { 'image/png': ['.png'], 'image/jpeg': ['.jpg', '.jpeg'] }
const DOCUMENT: AcceptMap = { 'application/pdf': ['.pdf'], 'text/plain': ['.txt'] }
const ECG_EXPORT: AcceptMap = { 'text/csv': ['.csv'], 'text/plain': ['.txt', '.tsv'] }

interface ModelDef {
  id: string
  label: string
  modality: string
  upload: { category: string; accept: AcceptMap; instruction: string } | null
  fields: SimpleField[]
}

/**
 * Declared-health options.
 *
 * `key` is what the scoring engine matches on and MUST NOT be edited casually —
 * the authoritative list is SYMPTOM_KEYS and RULES in
 * `apps/api/app/scoring.py`, mirrored in docs/TB.md. A key that does not match
 * fails silently: the rule simply never fires and the applicant is scored on
 * imaging alone. `label` is display text and is safe to reword.
 */
interface Option {
  key: string
  label: string
}

const SYMPTOMS: Option[] = [
  { key: 'cough_over_2_weeks', label: 'Cough lasting more than 2 weeks' },
  { key: 'weight_loss', label: 'Unexplained weight loss' },
  { key: 'night_sweats', label: 'Night sweats' },
  { key: 'haemoptysis', label: 'Coughing up blood' },
  { key: 'fever', label: 'Fever' },
]

const HISTORY_ONCE: Option[] = [
  { key: 'diabetes', label: 'Diabetes' },
  { key: 'hiv', label: 'HIV positive' },
  { key: 'household_tb_contact', label: 'Someone in the household has had TB' },
  { key: 'antibiotics_no_improvement', label: 'Took a course of antibiotics without improvement' },
  { key: 'smoker', label: 'Current or former smoker' },
]

const CARDIO: Option[] = [
  { key: 'hypertension', label: 'Hypertension' },
  { key: 'high_cholesterol', label: 'High cholesterol' },
  { key: 'family_heart_disease', label: 'Family history of heart disease' },
]

const SKIN_TYPES = ['I', 'II', 'III', 'IV', 'V', 'VI']

// The model registry drives the whole form. Adding or dropping an arm is one
// entry here (see docs/INTAKE_FORM.md and SPEC.md §6).
const MODELS: ModelDef[] = [
  {
    id: 'cxr_lung',
    label: 'Chest X-ray',
    modality: 'TorchXRayVision (DenseNet)',
    upload: {
      category: 'Chest X-ray',
      accept: { ...DICOM, ...PHOTO },
      instruction: 'Chest X-ray — .dcm, .png, or .jpg',
    },
    fields: [],
  },
  {
    id: 'mirai',
    label: 'Mirai',
    modality: 'Breast · mammography',
    upload: {
      category: 'Mammogram',
      accept: DICOM,
      instruction: 'Mammogram, 4 views — .dcm',
    },
    fields: [
      { kind: 'checkbox', key: 'family_breast_cancer', label: 'Family history of breast cancer' },
      { kind: 'checkbox', key: 'prior_biopsy', label: 'Prior breast biopsy' },
      {
        kind: 'select',
        key: 'brca_status',
        label: 'Known BRCA / genetic test result',
        data: ['Not tested', 'Negative', 'Positive'],
        placeholder: 'Not tested',
      },
    ],
  },
  {
    id: 'ham10000',
    label: 'HAM10000',
    modality: 'Dermoscopy · skin',
    upload: {
      category: 'Lesion photo',
      accept: PHOTO,
      instruction: 'Lesion photograph — .png or .jpg',
    },
    fields: [
      { kind: 'select', key: 'skin_type', label: 'Skin type (Fitzpatrick)', data: SKIN_TYPES, placeholder: 'Select' },
      { kind: 'checkbox', key: 'prior_skin_cancer', label: 'Prior skin cancer' },
      {
        kind: 'select',
        key: 'body_site',
        label: 'Body site',
        data: ['Head / neck', 'Upper limb', 'Trunk', 'Lower limb'],
        placeholder: 'Select',
      },
    ],
  },
  {
    id: 'eyepacs',
    label: 'EyePACS',
    modality: 'Retinopathy · fundus',
    upload: {
      category: 'Retinal photo',
      accept: { ...PHOTO, ...DICOM },
      instruction: 'Retinal / fundus photo — .png, .jpg, or .dcm',
    },
    fields: [
      {
        kind: 'select',
        key: 'diabetes_duration',
        label: 'Diabetes duration',
        data: ['No diabetes', 'Under 5 years', '5–10 years', 'Over 10 years'],
        placeholder: 'Select',
      },
      { kind: 'checkbox', key: 'hypertension', label: 'Hypertension' },
      { kind: 'checkbox', key: 'smoker', label: 'Current or former smoker' },
    ],
  },
  {
    id: 'ecg',
    label: '12-lead ECG',
    modality: 'Rhythm · conduction · ECG age',
    upload: {
      category: '12-lead ECG',
      // The signal the machine exports, not a picture of it: a scanned strip
      // holds 2.5 s of each lead at poor fidelity, and the models want ten.
      accept: ECG_EXPORT,
      instruction: 'ECG export with all 12 leads and a time column or sampling rate — .csv or .txt',
    },
    fields: [
      { kind: 'checkbox', key: 'palpitations', label: 'Palpitations or irregular heartbeat' },
      { kind: 'checkbox', key: 'known_arrhythmia', label: 'Known arrhythmia or pacemaker' },
    ],
  },
  {
    id: 'biobert',
    label: 'BioBERT',
    modality: 'Clinical NLP · EHR',
    upload: {
      category: 'Clinical note',
      accept: DOCUMENT,
      instruction: 'Clinical note / physician report — .pdf or .txt',
    },
    fields: [],
  },
  {
    id: 'xgboost',
    label: 'Blood panel and lifestyle',
    modality: 'Mortality · phenotypic age',
    upload: null,
    // The nine blood values are Levine's Phenotypic Age inputs, in the units a
    // Bangladeshi laboratory prints. The keys and units are read by
    // `apps/api/app/arms/mortality.py`; a value typed in the wrong unit is
    // refused there rather than silently scored decades older.
    fields: [
      { kind: 'number', key: 'albumin_g_dl', label: 'Serum albumin (g/dL)', description: 'Liver function test. Typical 3.5–5.0. The nine blood values are optional together: with all nine the phenotypic age is computed as well.' },
      { kind: 'number', key: 'creatinine_mg_dl', label: 'Serum creatinine (mg/dL)', description: 'Typical 0.6–1.2.' },
      { kind: 'number', key: 'glucose_mg_dl', label: 'Glucose (mg/dL)', description: 'Fasting if available. Typical 70–100.' },
      { kind: 'number', key: 'crp_mg_l', label: 'C-reactive protein (mg/L)', description: 'Typical under 3. Enter 0 for "below detection".' },
      { kind: 'number', key: 'lymphocyte_pct', label: 'Lymphocytes (%)', description: 'From the CBC differential. Typical 20–40.' },
      { kind: 'number', key: 'mcv_fl', label: 'Mean cell volume (fL)', description: 'From the CBC. Typical 80–100.' },
      { kind: 'number', key: 'rdw_pct', label: 'Red cell distribution width, RDW-CV (%)', description: 'From the CBC. Typical 11.5–14.5. Not RDW-SD.' },
      { kind: 'number', key: 'alp_u_l', label: 'Alkaline phosphatase (U/L)', description: 'Liver function test. Typical 40–130.' },
      { kind: 'number', key: 'wbc_10e3_ul', label: 'White blood cells (×10³/µL)', description: 'From the CBC. Typical 4–11.' },
      // Optional. These feed the kidney, liver and weight readings shown beside
      // the phenotypic age; they never move the score.
      { kind: 'number', key: 'ast_u_l', label: 'AST (U/L) — optional', description: 'Liver function test. With ALT and platelets gives the FIB-4 fibrosis index.' },
      { kind: 'number', key: 'alt_u_l', label: 'ALT (U/L) — optional' },
      { kind: 'number', key: 'platelets_10e3_ul', label: 'Platelets (×10³/µL) — optional', description: 'From the CBC.' },
      { kind: 'number', key: 'sbp_mmhg', label: 'Systolic blood pressure (mm Hg) — optional', description: 'Seated, at rest.' },
      { kind: 'number', key: 'height_cm', label: 'Height (cm)' },
      { kind: 'number', key: 'weight_kg', label: 'Weight (kg)' },
      { kind: 'select', key: 'alcohol', label: 'Alcohol use', data: ['None', 'Occasionally', 'Regularly'], placeholder: 'Select' },
      { kind: 'select', key: 'activity', label: 'Physical activity', data: ['Sedentary', 'Light', 'Moderate', 'Active'], placeholder: 'Select' },
      { kind: 'select', key: 'occupation', label: 'Occupation', data: ['Office / professional', 'Manual / physical', 'Retired', 'Student', 'Not employed'], placeholder: 'Select' },
      { kind: 'checkbox', key: 'smoker', label: 'Current or former smoker' },
    ],
  },
  {
    id: 'neuro',
    label: 'Neuro MRI',
    modality: '3D brain · MONAI',
    upload: {
      category: 'MRI scan',
      accept: DICOM,
      instruction: 'Brain MRI — .dcm',
    },
    fields: [
      { kind: 'checkbox', key: 'memory_concerns', label: 'Memory concerns' },
      { kind: 'checkbox', key: 'speech_concerns', label: 'Speech concerns' },
      { kind: 'checkbox', key: 'mobility_concerns', label: 'Coordination / mobility concerns' },
    ],
  },
]

const MAX_FILE_BYTES = 50 * 1024 * 1024
const MAX_FACE_BYTES = 10 * 1024 * 1024

interface IntakeForm {
  reference: string
  name: string
  phone: string
  email: string
  dob: string
  sex: string | null
  coverageType: string | null
  coverageAmount: number | null
  policyTerm: string | null
  selectedModels: string[]
  modelFields: Record<string, ModelValues>
}

interface EvidenceFile {
  id: string
  name: string
  size: number
  fileType: string
  // The File itself, not just its name: this is what is uploaded at submit.
  file: File
}

function formatSize(b: number) {
  if (b < 1024) return `${b} B`
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(0)} KB`
  return `${(b / (1024 * 1024)).toFixed(1)} MB`
}

/**
 * Turn the form's per-model state into the `declared_history` shape the API
 * stores and the scoring engine reads (DATABASE.md §C):
 *
 *   { cxr_lung: { symptoms: { cough_over_2_weeks: true, ... },
 *                 history:  { prior_tb: true, ... } } }
 *
 * The form tracks ticked boxes as arrays of keys; the contract is an explicit
 * true/false per option. Sending the array instead would mean every rule reads
 * a missing key as false and never fires.
 */
function declaredHistory(
  selectedModels: string[],
  modelFields: Record<string, ModelValues>,
): Record<string, Record<string, unknown>> {
  const out: Record<string, Record<string, unknown>> = {}

  for (const id of selectedModels) {
    const values = modelFields[id] ?? {}
    const block: Record<string, unknown> = {}

    if (id === 'cxr_lung') {
      const flags = (group: Option[], picked: unknown) =>
        Object.fromEntries(
          group.map((o) => [o.key, ((picked as string[]) ?? []).includes(o.key)]),
        )

      block.symptoms = flags(SYMPTOMS, values.symptoms)
      block.history = {
        ...flags(HISTORY_ONCE, values.history),
        prior_tb: values.prior_tb === true,
        // null (unanswered) is gated at submit, so this is only ever a real answer.
        prior_tb_treatment_completed: values.prior_tb_treatment_completed === 'yes',
      }
      block.cardio = flags(CARDIO, values.cardio)
    } else {
      // Every other arm's fields are already scalars keyed by `key`.
      Object.assign(block, values)
    }

    out[id] = block
  }

  return out
}

function bool(v: Scalar | undefined) {
  return v === true
}

/**
 * The client's portal sign-in, on the confirmation screen.
 *
 * When it was emailed there is nothing to hand over, so only the id is shown.
 * When it was not, this is the one moment the password exists on a screen: the
 * API keeps only its hash and no endpoint can return it again, so the operator
 * gives it to the client who is sitting opposite them.
 */
function PortalSignIn({ portal }: { portal: PortalCredentials }) {
  if (portal.emailed) {
    return (
      <Paper p="md" bd="1px solid var(--mantine-color-default-border)">
        <Text size="sm" fw={600}>Client portal sign-in sent</Text>
        <Text size="sm" c="dimmed" mt={4}>
          Emailed to {portal.email}. Their portal ID is{' '}
          <Text span ff="monospace" fw={600} c="bright">{portal.portalId}</Text>.
        </Text>
      </Paper>
    )
  }

  const rows = [
    { label: 'Portal ID', value: portal.portalId },
    { label: 'Password', value: portal.password ?? '' },
  ]

  return (
    <Paper p="md" bd="1px solid var(--mantine-color-yellow-filled)">
      <Text size="sm" fw={600}>Give the client their portal sign-in now</Text>
      <Text size="sm" c="dimmed" mt={4}>
        {portal.email
          ? `It could not be emailed to ${portal.email}.`
          : 'No email address was given.'}{' '}
        The password is not stored and cannot be shown again after you leave this page.
      </Text>
      <Table mt="sm" withRowBorders={false} verticalSpacing={4}>
        <Table.Tbody>
          {rows.map((row) => (
            <Table.Tr key={row.label}>
              <Table.Td w={90}>
                <Text size="xs" c="dimmed">{row.label}</Text>
              </Table.Td>
              <Table.Td>
                <Text ff="monospace" fw={600}>{row.value}</Text>
              </Table.Td>
              <Table.Td w={80} ta="right">
                <CopyButton value={row.value}>
                  {({ copied, copy }) => (
                    <Button size="compact-xs" variant="light" onClick={copy}>
                      {copied ? 'Copied' : 'Copy'}
                    </Button>
                  )}
                </CopyButton>
              </Table.Td>
            </Table.Tr>
          ))}
        </Table.Tbody>
      </Table>
      <Text size="xs" c="dimmed" mt="sm">
        They sign in from the Client tab on the sign-in page.
      </Text>
    </Paper>
  )
}

export function IntakePage() {
  const form = useForm<IntakeForm>({
    initialValues: {
      reference: '',
      name: '',
      phone: '',
      email: '',
      dob: '',
      sex: null,
      coverageType: null,
      coverageAmount: null,
      policyTerm: null,
      selectedModels: [],
      modelFields: {},
    },
  })

  // Which models actually run is a fact about the backend. The form used to
  // offer all seven as though they worked; only the chest X-ray does, and an
  // operator attaching a mammogram got no score and no explanation.
  const { data: catalogue = [] } = useQuery({
    queryKey: ['models'],
    queryFn: getModels,
    staleTime: 5 * 60 * 1000,
  })
  const availability = new Map(catalogue.map((m) => [m.id, m]))
  const isAvailable = (id: string) => availability.get(id)?.available ?? false

  const [modelFiles, setModelFiles] = useState<Record<string, EvidenceFile[]>>({})
  const [facePhoto, setFacePhoto] = useState<File | null>(null)
  const [facePreview, setFacePreview] = useState<string | null>(null)
  const [rejectNote, setRejectNote] = useState<Record<string, string | null>>({})
  // The review step between pressing submit and anything being scored.
  // `classified` is null until the API answers; `overrides` holds the
  // operator's corrections, keyed by filename.
  const [reviewOpen, setReviewOpen] = useState(false)
  const [classified, setClassified] = useState<ClassifyResponse | null>(null)
  const [overrides, setOverrides] = useState<Record<string, string>>({})

  const [submitting, setSubmitting] = useState(false)
  const [submitted, setSubmitted] = useState<SubmitResponse | null>(null)
  const [submitError, setSubmitError] = useState<string | null>(null)
  const navigate = useNavigate()

  // The reference is GENERATED BY THE DATABASE (applicants_ref_seq -> HL-<seq>)
  // by a trigger at INSERT, so there is nothing to preview and the operator
  // never types it. The real value comes back in the submit response.

  const toggleSet = (modelId: string, key: string, value: string) => {
    const block = (form.values.modelFields[modelId]?.[key] as string[]) ?? []
    const next = block.includes(value)
      ? block.filter((v) => v !== value)
      : [...block, value]
    setField(modelId, key, next)
  }

  const setField = (modelId: string, key: string, value: Scalar) => {
    form.setFieldValue('modelFields', {
      ...form.values.modelFields,
      [modelId]: { ...(form.values.modelFields[modelId] ?? {}), [key]: value },
    })
  }

  const toggleModel = (id: string) => {
    // A model that cannot score is not selectable. Letting someone attach a
    // mammogram that will never be read wastes their time and the client's.
    if (!isAvailable(id)) return
    const has = form.values.selectedModels.includes(id)
    form.setFieldValue(
      'selectedModels',
      has
        ? form.values.selectedModels.filter((m) => m !== id)
        : [...form.values.selectedModels, id],
    )
  }

  const selected = MODELS.filter((m) => form.values.selectedModels.includes(m.id))

  const addModelFiles = (modelId: string, dropped: File[], fileType: string) => {
    setRejectNote((p) => ({ ...p, [modelId]: null }))
    const added: EvidenceFile[] = dropped.map((f) => ({
      id: crypto.randomUUID(),
      name: f.name,
      size: f.size,
      fileType,
      file: f,
    }))
    setModelFiles((prev) => ({ ...prev, [modelId]: [...(prev[modelId] ?? []), ...added] }))

    // Classify as the file lands rather than at submit. By the time the
    // operator finishes the form the answer is already cached, so the review
    // screen opens instantly instead of making them wait with a client
    // watching. A failure here is silent: submit re-classifies anyway, and an
    // error about a background request would mean nothing to the operator.
    void classifyEvidence(dropped)
      .then((result) => {
        setClassified((prev) =>
          prev ? { ...prev, files: [...prev.files, ...result.files] } : result,
        )
      })
      .catch(() => {})
  }

  const addModelReject = (modelId: string, rejects: { file: File }[]) => {
    const tooBig = rejects.some((r) => r.file.size > MAX_FILE_BYTES)
    setRejectNote((p) => ({
      ...p,
      [modelId]: tooBig
        ? 'File rejected — the 50 MB limit was exceeded.'
        : 'File rejected — check the accepted type for this model.',
    }))
  }

  const removeModelFile = (modelId: string, id: string) => {
    const gone = (modelFiles[modelId] ?? []).find((f) => f.id === id)
    setModelFiles((prev) => ({
      ...prev,
      [modelId]: (prev[modelId] ?? []).filter((f) => f.id !== id),
    }))
    // Drop its classification as well. A row left behind for a file that is no
    // longer attached would sit unresolved and block submit forever.
    if (gone) {
      setClassified((prev) =>
        prev ? { ...prev, files: prev.files.filter((f) => f.filename !== gone.name) } : prev,
      )
      setOverrides((prev) => {
        const { [gone.name]: _removed, ...rest } = prev
        return rest
      })
    }
  }

  const setFace = (file: File | null) => {
    if (facePreview) URL.revokeObjectURL(facePreview)
    setFacePhoto(file)
    setFacePreview(file ? URL.createObjectURL(file) : null)
  }

  const addFacePhoto = (dropped: File[]) => {
    setRejectNote((p) => ({ ...p, face: null }))
    if (dropped.length === 0) return
    setFace(dropped[0])
  }

  const addFaceReject = (rejects: { file: File }[]) => {
    const tooBig = rejects.some((r) => r.file.size > MAX_FACE_BYTES)
    setRejectNote((p) => ({
      ...p,
      face: tooBig
        ? 'Face photo rejected — the 10 MB limit was exceeded.'
        : 'Face photo rejected — use a .png or .jpg image.',
    }))
  }

  const modelHasUpload = (m: ModelDef) => (modelFiles[m.id] ?? []).length > 0

  /**
   * "Previously treated for TB" ticked but the follow-up left blank would be
   * sent as null and read downstream as "did not complete" — silently scoring
   * the applicant 25 points higher than an answered "yes" would. Require it.
   */
  const tbFollowUpAnswered = (() => {
    if (!form.values.selectedModels.includes('cxr_lung')) return true
    const values = form.values.modelFields.cxr_lung
    if (!bool(values?.prior_tb)) return true
    return (
      values?.prior_tb_treatment_completed === 'yes' ||
      values?.prior_tb_treatment_completed === 'no'
    )
  })()

  const modelsSectionComplete =
    selected.length > 0 &&
    selected.every((m) => m.upload === null || modelHasUpload(m)) &&
    tbFollowUpAnswered

  const sections = [
    // The identity photo is deliberately not required. It is biometric data
    // that no model reads, so demanding it would collect the most sensitive
    // thing on the form for no benefit (SPEC §9, PII minimisation).
    Boolean(form.values.name.trim()) && Boolean(form.values.phone.trim()),
    Boolean(form.values.coverageType) && (form.values.coverageAmount ?? 0) > 0,
    modelsSectionComplete,
  ]
  const completeCount = sections.filter(Boolean).length

  const canSubmit = sections[0] && sections[1] && modelsSectionComplete

  /** Every attached file, paired with the model panel it came from. */
  const uploads = selected.flatMap((m) =>
    (modelFiles[m.id] ?? []).map((f) => ({ file: f.file, arm: m.id })),
  )

  /**
   * Submit opens the review step rather than sending. Nothing is scored until
   * the operator has confirmed what each document is, because a model given the
   * wrong kind of file answers confidently instead of failing.
   */
  const handleSubmit = async () => {
    if (!canSubmit) return
    setSubmitError(null)
    setReviewOpen(true)

    // Normally already done as the files landed. This covers the case where
    // that background request failed or is still in flight.
    if (!classified || classified.files.length !== uploads.length) {
      try {
        setClassified(await classifyEvidence(uploads.map((u) => u.file)))
      } catch {
        setClassified({ files: [], choices: [] })
      }
    }
  }

  /** Called from the review step, once every file has a confirmed kind. */
  const sendApplication = async () => {
    setSubmitting(true)
    setSubmitError(null)

    const kindFor = (file: File) => {
      const proposed = classified?.files.find((f) => f.filename === file.name)
      return overrides[file.name] ?? proposed?.kind ?? 'unknown'
    }

    try {
      const result = await submitApplication({
        payload: {
          applicant: {
            name: form.values.name.trim(),
            phone: form.values.phone.trim(),
            dateOfBirth: form.values.dob || null,
            sex: form.values.sex,
            email: form.values.email.trim() || null,
          },
          coverage: {
            coverageType: form.values.coverageType,
            coverageAmount: form.values.coverageAmount,
            policyTerm: form.values.policyTerm,
          },
          modelsRequested: form.values.selectedModels,
          declaredHistory: declaredHistory(form.values.selectedModels, form.values.modelFields),
        },
        files: uploads.map((u) => ({ ...u, kind: kindFor(u.file) })),
        facePhoto: facePhoto,
      })
      setReviewOpen(false)
      setSubmitted(result)
    } catch (err) {
      // Keep the form exactly as it was. The operator has a client sitting
      // opposite and must not have to re-enter anything to retry.
      setSubmitError(err instanceof Error ? err.message : 'The application could not be submitted.')
    } finally {
      setSubmitting(false)
    }
  }

  if (submitted) {
    return (
      <Stack gap="md" maw={560}>
        <Alert icon={<IconCircleCheck size={18} />} color="teal" title="Application submitted">
          <Text size="sm">
            Reference <Text span ff="monospace" fw={600}>{submitted.reference}</Text>{' '}
            is in the queue. The models are reading the evidence now — the queue
            updates on its own when the result lands.
          </Text>
        </Alert>
        {submitted.portal && <PortalSignIn portal={submitted.portal} />}
        <Group>
          <Button size="xs" onClick={() => navigate('/queue')}>
            Back to queue
          </Button>
          <Button
            size="xs"
            variant="light"
            onClick={() => navigate(`/applications/${submitted.id}`)}
          >
            Open this application
          </Button>
        </Group>
      </Stack>
    )
  }

  return (
    <Stack gap="lg" maw={980}>
      {/* Sticky progress hint */}
      <Paper
        p="sm"
        pos="sticky"
        top={0}
        style={{ zIndex: 10 }}
        bd="1px solid var(--mantine-color-default-border)"
        bg="var(--mantine-color-body)"
      >
        <Group justify="space-between">
          <Text size="xs" c="dimmed">
            {completeCount} of 3 sections complete
          </Text>
          <Text size="xs" fw={600} c={canSubmit ? 'teal' : 'dimmed'}>
            {canSubmit ? 'Ready to submit' : 'Not ready to submit'}
          </Text>
        </Group>
      </Paper>

      <div>
        <Text size="xs" c="dimmed" tt="uppercase" fw={600} className="hl-eyebrow">
          New application
        </Text>
        <Text size="lg" fw={600}>
          Review a new client
        </Text>
        <Text size="sm" c="dimmed" maw={680}>
          Fill this in with the client in front of you. One page, one submit —
          nothing is lost if you jump around or the client corrects themselves.
          The reference number is assigned by the system when you submit.
        </Text>
      </div>

      {/* ── Section 1 · Applicant ─────────────────────────────── */}
      <Section n="1" title="Applicant" complete={sections[0]}>
        <TextInput
          label="Reference"
          description="Generated by the database (HL-&lt;seq&gt;) when the application is saved. Read-only."
          readOnly
          disabled
          placeholder="assigned on submit"
          value=""
        />

        <SimpleGrid cols={{ base: 1, md: 2 }} spacing="lg" mt="md">
          <Stack gap="sm">
            <Group grow align="flex-start">
              <TextInput label="Name" required placeholder="Client name" {...form.getInputProps('name')} />
              <TextInput label="Phone" required placeholder="+880 1XXXXXXXXX" {...form.getInputProps('phone')} />
            </Group>
            <TextInput
              label="Email"
              type="email"
              placeholder="client@example.com"
              description="Optional. Their portal sign-in is sent here. Without it, you are shown the sign-in to hand over."
              {...form.getInputProps('email')}
            />
            <Group grow align="flex-start">
              <TextInput label="Date of birth" type="date" {...form.getInputProps('dob')} />
              <Select
                label="Sex"
                placeholder="Prefer not to say"
                data={['Female', 'Male', 'Other', 'Prefer not to say']}
                clearable
                {...form.getInputProps('sex')}
              />
            </Group>
          </Stack>

          <FacePhotoUpload
            file={facePhoto}
            preview={facePreview}
            note={rejectNote.face}
            onDrop={addFacePhoto}
            onReject={addFaceReject}
            onRemove={() => setFace(null)}
          />
        </SimpleGrid>
      </Section>

      <Divider my="xs" />

      {/* ── Section 2 · Coverage requested ─────────────────────── */}
      <Section n="2" title="Coverage requested" complete={sections[1]}>
        <Group align="flex-end">
          <Select
            label="Coverage type"
            placeholder="Select"
            required
            data={['Life', 'Health', 'Critical illness']}
            {...form.getInputProps('coverageType')}
          />
          <NumberInput
            label="Coverage amount (BDT)"
            placeholder="1,000,000"
            required
            thousandSeparator=","
            min={0}
            {...form.getInputProps('coverageAmount')}
          />
          <Select
            label="Policy term"
            placeholder="Years"
            data={['1', '5', '10', '20']}
            clearable
            {...form.getInputProps('policyTerm')}
          />
        </Group>
      </Section>

      <Divider my="xs" />

      {/* ── Section 3 · Models ─────────────────────────────────── */}
      <Section n="3" title="Models" complete={sections[2]}>
        <Text size="sm" c="dimmed">
          Pick what you want screened. Each model you select opens a panel below
          asking for its report and its questions.
        </Text>

        <Group align="flex-start" wrap="nowrap" gap="lg">
          {/* Vertical menu. Availability comes from the API, not this file. */}
          <Stack gap={6} w={280} style={{ flexShrink: 0 }}>
            {MODELS.map((m) => {
              const on = form.values.selectedModels.includes(m.id)
              const info = availability.get(m.id)
              const ready = info?.available ?? false
              return (
                <Paper
                  key={m.id}
                  p="xs"
                  withBorder
                  bd={
                    on
                      ? '1px solid var(--mantine-color-clinical-3)'
                      : '1px solid var(--mantine-color-default-border)'
                  }
                  style={{
                    cursor: ready ? 'pointer' : 'not-allowed',
                    opacity: ready ? 1 : 0.55,
                  }}
                  onClick={() => toggleModel(m.id)}
                  aria-disabled={!ready}
                >
                  <Group gap="xs" wrap="nowrap" align="flex-start">
                    <Checkbox
                      checked={on}
                      disabled={!ready}
                      readOnly
                      mt={2}
                      aria-label={m.label}
                    />
                    <Stack gap={2} style={{ flex: 1, minWidth: 0 }}>
                      <Group gap={6} wrap="nowrap" justify="space-between">
                        <Text size="sm" fw={600}>
                          {info?.label ?? m.label}
                        </Text>
                        {!ready && (
                          <Badge size="xs" color="gray" variant="outline">
                            Not built yet
                          </Badge>
                        )}
                      </Group>
                      {/* What it answers, not what file it eats — that is the
                          question an operator is actually asking. */}
                      <Text size="xs" c="dimmed">
                        {info?.screensFor ?? m.modality}
                      </Text>
                    </Stack>
                  </Group>
                </Paper>
              )
            })}
            <Text size="xs" c="dimmed" mt={4}>
              Greyed-out models are on the roadmap but produce no score yet, so
              they cannot be selected.
            </Text>
          </Stack>

          {/* Pop-out panels for selected models */}
          <Stack gap="md" style={{ flex: 1, minWidth: 0 }}>
            {selected.length === 0 && (
              <Text size="sm" c="dimmed">
                Nothing selected yet — pick at least one model from the menu.
              </Text>
            )}
            {selected.map((m) => (
              <Paper key={m.id} bd="1px solid var(--mantine-color-default-border)" p="md">
                <Group justify="space-between" align="flex-start" mb={4}>
                  <Text fw={600} size="sm">
                    {availability.get(m.id)?.label ?? m.label}
                    <Text span c="dimmed" fw={400}>
                      {' '}
                      · screens for {availability.get(m.id)?.screensFor ?? m.modality}
                    </Text>
                  </Text>
                  <Badge size="xs" color="teal" variant="light">
                    {availability.get(m.id)?.armVersion ?? 'ready'}
                  </Badge>
                </Group>
                {/* The caveat travels with the model, not a document. */}
                {availability.get(m.id)?.validation && (
                  <Text size="xs" c="yellow.7" mb="sm">
                    {availability.get(m.id)?.validation}
                  </Text>
                )}

                {m.upload ? (
                  <PanelUpload
                    model={m}
                    files={modelFiles[m.id] ?? []}
                    note={rejectNote[m.id]}
                    onDrop={(files) => addModelFiles(m.id, files, m.upload!.category)}
                    onReject={(rejects) => addModelReject(m.id, rejects)}
                    onRemove={(id) => removeModelFile(m.id, id)}
                  />
                ) : (
                  <Alert color="gray" variant="light" mb="md">
                    <Text size="sm">No report needed — complete the demographic form.</Text>
                  </Alert>
                )}

                <ModelFieldControls
                  model={m}
                  values={form.values.modelFields[m.id] ?? {}}
                  setField={setField}
                  toggleSet={toggleSet}
                />
              </Paper>
            ))}
          </Stack>
        </Group>
      </Section>

      <Divider my="xs" />

      {/*
        A failed submit must never clear the form: the operator has a client in
        front of them, and re-entering everything is the difference between a
        retry and a lost appointment.
      */}
      {submitError && (
        <Alert
          color="red"
          variant="light"
          icon={<IconAlertCircle size={16} />}
          title="The application was not submitted"
        >
          <Text size="sm">{submitError}</Text>
          <Text size="xs" c="dimmed" mt={4}>
            Nothing has been lost — everything you entered is still here. Try again.
          </Text>
        </Alert>
      )}

      <Group justify="space-between" align="flex-start">
        <Text size="xs" c="dimmed" maw={460}>
          Needs a name and phone, a coverage type and amount, and at least one
          model with its report attached. Scoring starts as soon as you submit
          and takes a few seconds — the queue updates itself.
        </Text>
        <Button size="sm" disabled={!canSubmit} loading={submitting} onClick={handleSubmit}>
          Submit application
        </Button>
      </Group>
      <EvidenceReview
        opened={reviewOpen}
        result={classified}
        overrides={overrides}
        onOverride={(filename, kind) =>
          setOverrides((prev) => ({ ...prev, [filename]: kind }))
        }
        onConfirm={() => void sendApplication()}
        onCancel={() => setReviewOpen(false)}
        submitting={submitting}
      />

      {submitting && (
        <Group gap="xs" c="dimmed">
          <Loader size={14} />
          <Text size="xs">Uploading evidence and creating the application…</Text>
        </Group>
      )}
    </Stack>
  )
}

function FacePhotoUpload({
  file,
  preview,
  note,
  onDrop,
  onReject,
  onRemove,
}: {
  file: File | null
  preview: string | null
  note: string | null
  onDrop: (files: File[]) => void
  onReject: (rejects: { file: File }[]) => void
  onRemove: () => void
}) {
  return (
    <Paper bd="1px solid var(--mantine-color-default-border)" p="md" mt="md">
      <Group gap="xs" mb={4}>
        <Text fw={600} size="sm">
          Identity photo
        </Text>
        <Badge size="xs" color="gray" variant="outline">
          Optional
        </Badge>
      </Group>
      <Text size="xs" c="dimmed" mb="sm">
        For your own records only. No model reads it, and it is never shown next
        to the risk score — a face beside a score can only bias the decision.
        Skip it if you do not need it.
      </Text>

      {file && preview ? (
        <Group align="flex-start" gap="md">
          <Box
            w={96}
            h={96}
            style={{
              borderRadius: 6,
              overflow: 'hidden',
              border: '1px solid var(--mantine-color-default-border)',
              flexShrink: 0,
            }}
          >
            <img
              src={preview}
              alt="Face photo preview"
              style={{ width: '100%', height: '100%', objectFit: 'cover' }}
            />
          </Box>
          <Stack gap={4} align="flex-start">
            <Text ff="monospace" size="sm">
              {file.name}
            </Text>
            <Text size="xs" c="dimmed">
              {formatSize(file.size)}
            </Text>
            <Button size="xs" variant="subtle" color="red" onClick={onRemove}>
              Remove
            </Button>
          </Stack>
        </Group>
      ) : (
        <Dropzone
          accept={PHOTO}
          maxSize={MAX_FACE_BYTES}
          multiple={false}
          onDrop={onDrop}
          onReject={onReject}
        >
          <Group justify="center" py="md" style={{ pointerEvents: 'none' }}>
            <Text size="sm" c="dimmed">
              Drop the client’s face photo here, or click to browse — .png or
              .jpg, max 10 MB.
            </Text>
          </Group>
        </Dropzone>
      )}

      {note && (
        <Alert color="red" variant="light" icon={<IconAlertCircle size={16} />} mt="sm">
          <Text size="sm">{note}</Text>
        </Alert>
      )}
    </Paper>
  )
}

function PanelUpload({
  model,
  files,
  note,
  onDrop,
  onReject,
  onRemove,
}: {
  model: ModelDef
  files: EvidenceFile[]
  note: string | null
  onDrop: (files: File[]) => void
  onReject: (rejects: { file: File }[]) => void
  onRemove: (id: string) => void
}) {
  const upload = model.upload!
  return (
    <Box mb="md">
      <Alert icon={<IconFileUpload size={16} />} color="clinical" variant="light" mb="sm">
        <Text size="sm">
          Please submit: <Text span fw={600}>{upload.instruction}</Text>
        </Text>
      </Alert>

      <Dropzone
        accept={upload.accept}
        maxSize={MAX_FILE_BYTES}
        multiple
        onDrop={onDrop}
        onReject={onReject}
      >
        <Group justify="center" gap="xl" py="sm" style={{ pointerEvents: 'none' }}>
          <Dropzone.Accept>
            <IconFileUpload size={24} color="var(--mantine-color-clinical-3)" />
          </Dropzone.Accept>
          <Dropzone.Reject>
            <IconAlertCircle size={24} color="var(--mantine-color-red-5)" />
          </Dropzone.Reject>
          <Dropzone.Idle>
            <IconFileUpload size={24} color="var(--mantine-color-dimmed)" />
          </Dropzone.Idle>
          <Stack gap={2} align="center">
            <Text fw={500} size="sm">
              Drop files here or click to browse
            </Text>
            <Text size="xs" c="dimmed">
              {upload.instruction} · max 50 MB per file
            </Text>
          </Stack>
        </Group>
      </Dropzone>

      {note && (
        <Alert color="red" variant="light" icon={<IconAlertCircle size={16} />} mt="sm">
          <Text size="sm">{note}</Text>
        </Alert>
      )}

      {files.length > 0 && (
        <Table mt="sm">
          <Table.Thead>
            <Table.Tr>
              <Table.Th>File</Table.Th>
              <Table.Th>Size</Table.Th>
              <Table.Th w={60} />
            </Table.Tr>
          </Table.Thead>
          <Table.Tbody>
            {files.map((f) => (
              <Table.Tr key={f.id}>
                <Table.Td ff="monospace">{f.name}</Table.Td>
                <Table.Td>{formatSize(f.size)}</Table.Td>
                <Table.Td>
                  <ActionIcon
                    size="sm"
                    variant="subtle"
                    color="red"
                    aria-label="Remove file"
                    onClick={() => onRemove(f.id)}
                  >
                    <IconX size={14} />
                  </ActionIcon>
                </Table.Td>
              </Table.Tr>
            ))}
          </Table.Tbody>
        </Table>
      )}
    </Box>
  )
}

function ModelFieldControls({
  model,
  values,
  setField,
  toggleSet,
}: {
  model: ModelDef
  values: ModelValues
  setField: (modelId: string, key: string, value: Scalar) => void
  toggleSet: (modelId: string, key: string, value: string) => void
}) {
  if (model.id === 'cxr_lung') {
    return (
      <CxrPanel values={values} setField={setField} toggleSet={toggleSet} />
    )
  }

  if (model.fields.length === 0) {
    return (
      <Text size="xs" c="dimmed">
        No additional questions — the {model.label} model reads the uploaded report directly.
      </Text>
    )
  }

  return (
    <Stack gap="sm">
      {model.fields.map((f) => {
        if (f.kind === 'checkbox') {
          return (
            <Checkbox
              key={f.key}
              label={f.label}
              checked={bool(values[f.key])}
              onChange={(e) => setField(model.id, f.key, e.currentTarget.checked)}
            />
          )
        }
        if (f.kind === 'select') {
          return (
            <Select
              key={f.key}
              label={f.label}
              placeholder={f.placeholder ?? 'Select'}
              data={f.data}
              clearable
              value={typeof values[f.key] === 'string' ? (values[f.key] as string) : null}
              onChange={(v) => setField(model.id, f.key, v)}
            />
          )
        }
        return (
          <NumberInput
            key={f.key}
            label={f.label}
            description={f.description}
            min={0}
            value={typeof values[f.key] === 'number' ? (values[f.key] as number) : undefined}
            onChange={(v) => setField(model.id, f.key, v === '' ? null : v)}
          />
        )
      })}
    </Stack>
  )
}

function CxrPanel({
  values,
  setField,
  toggleSet,
}: {
  values: ModelValues
  setField: (modelId: string, key: string, value: Scalar) => void
  toggleSet: (modelId: string, key: string, value: string) => void
}) {
  const modelId = 'cxr_lung'
  const sym = (values.symptoms as string[]) ?? []
  const hist = (values.history as string[]) ?? []
  const cardio = (values.cardio as string[]) ?? []

  return (
    <Stack gap="md">
      {/* Current symptoms */}
      <Box>
        <Text fw={600} size="sm" mb="xs">
          Current symptoms
        </Text>
        <Stack gap="xs">
          {SYMPTOMS.map((s) => (
            <Checkbox
              key={s.key}
              label={s.label}
              checked={sym.includes(s.key)}
              onChange={() => toggleSet(modelId, 'symptoms', s.key)}
            />
          ))}
        </Stack>
      </Box>

      {/* TB history */}
      <Box>
        <Text fw={600} size="sm" mb="xs">
          Medical history
        </Text>
        <Stack gap="xs">
          <Checkbox
            label="Previously treated for TB"
            checked={bool(values.prior_tb)}
            onChange={(e) => {
              setField(modelId, 'prior_tb', e.currentTarget.checked)
              // Clear the follow-up when the parent is un-ticked, so a stale
              // answer cannot be submitted for someone with no TB history.
              if (!e.currentTarget.checked) {
                setField(modelId, 'prior_tb_treatment_completed', null)
              }
            }}
          />
          {bool(values.prior_tb) && (
            <Box pl="lg">
              {/*
                Yes/No rather than a checkbox. An unticked box cannot say whether
                the course was not completed or the question was never asked, and
                the two mean different things: a completed course lowers the score
                by 25, an incomplete one does not. Unanswered is sent as null and
                gated at submit rather than guessed.
              */}
              <Radio.Group
                label="Completed the full course of treatment"
                value={(values.prior_tb_treatment_completed as string) ?? ''}
                onChange={(v) => setField(modelId, 'prior_tb_treatment_completed', v)}
              >
                <Group gap="lg" mt={6}>
                  <Radio value="yes" label="Yes" />
                  <Radio value="no" label="No" />
                </Group>
              </Radio.Group>
            </Box>
          )}
          {HISTORY_ONCE.map((h) => (
            <Checkbox
              key={h.key}
              label={h.label}
              checked={hist.includes(h.key)}
              onChange={() => toggleSet(modelId, 'history', h.key)}
            />
          ))}
        </Stack>
      </Box>

      {/* Cardio */}
      <Box>
        <Text fw={600} size="sm" mb="xs">
          Cardiovascular
        </Text>
        <Stack gap="xs">
          {CARDIO.map((c) => (
            <Checkbox
              key={c.key}
              label={c.label}
              checked={cardio.includes(c.key)}
              onChange={() => toggleSet(modelId, 'cardio', c.key)}
            />
          ))}
        </Stack>
      </Box>
    </Stack>
  )
}
