/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Can the API reach the database?
         * @description Always answers 200, even when the database is unreachable — the point is
         *     to report the state, not to fail. Use it when the database lives on another
         *     machine and you need to know whether this one can see it.
         */
        get: operations["health_database_api_health_database_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Onboard Carrier Tenant & Admin
         * @description Register a new Subscribing Carrier Tenant and initial Tenant Admin account.
         */
        post: operations["register_tenant_api_auth_register_tenant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate User & Set Session Cookie
         * @description Authenticate user with email and password, setting an httpOnly session cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Authenticated User Session
         * @description Verify current httpOnly session cookie and return user details.
         */
        get: operations["get_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout User & Clear Session Cookie
         * @description Clear httpOnly session cookie.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The review queue
         * @description Newest first, scoped to the signed-in user's carrier.
         */
        get: operations["list_applications_api_applications_get"];
        put?: never;
        /**
         * Submit an application with its evidence
         * @description Store the application and its evidence, then score it in the background.
         *
         *     Scoring is not done inline: model inference takes seconds, and the operator
         *     has a client sitting opposite. They get a reference immediately, and the
         *     queue shows the result when it lands.
         */
        post: operations["submit_application_api_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything the review screen needs, in one call */
        get: operations["get_application_api_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record the underwriter's decision (write-once)
         * @description One decision per application, enforced by the database.
         *
         *     The built-in admin cannot decide: `underwriter_id` is a real foreign key,
         *     and a decision has to be attributable to a person who can be held to it.
         */
        post: operations["record_decision_api_applications__application_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The audit trail, with its hash chain verified
         * @description Verification runs on every read rather than on a schedule — an audit
         *     trail nobody checks is decoration.
         */
        get: operations["get_audit_trail_api_applications__application_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve one stored image
         * @description Evidence images and heatmaps, by id.
         *
         *     Files are served through the API rather than from a static folder so that
         *     every read is checked against the caller's tenant. Health data on a public
         *     URL would be a breach whatever the filename.
         */
        get: operations["get_file_api_files__file_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Notifications
         * @description Newest first, for the signed-in user only.
         */
        get: operations["list_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_api_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustmentSchema */
        AdjustmentSchema: {
            /** Key */
            key: string;
            /** Points */
            points: number;
            /** Reason */
            reason: string;
        };
        /** ApplicantIn */
        ApplicantIn: {
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Dateofbirth */
            dateOfBirth?: string | null;
            /** Sex */
            sex?: string | null;
        };
        /** ApplicationDetailSchema */
        ApplicationDetailSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reference */
            reference: string;
            status: components["schemas"]["ApplicationStatus"];
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
            /** Evaluatedat */
            evaluatedAt?: string | null;
            applicant: components["schemas"]["ApplicantIn"];
            coverage: components["schemas"]["CoverageIn"];
            /** Modelsrequested */
            modelsRequested?: string[];
            /** Declaredhistory */
            declaredHistory?: {
                [key: string]: unknown;
            };
            score?: components["schemas"]["ScoreSchema"] | null;
            /** Adjustments */
            adjustments?: components["schemas"]["AdjustmentSchema"][];
            /** Findings */
            findings?: components["schemas"]["FindingSchema"][];
            modelInfo?: components["schemas"]["ModelInfoSchema"] | null;
            /** Files */
            files?: components["schemas"]["FileSchema"][];
            decision?: components["schemas"]["DecisionSchema"] | null;
            /** Errors */
            errors?: string[];
        };
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "submitted" | "processing" | "insufficient_evidence" | "scored" | "decided";
        /** AuditEntrySchema */
        AuditEntrySchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Eventtype */
            eventType: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Actorname */
            actorName?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** AuditTrailSchema */
        AuditTrailSchema: {
            /** Entries */
            entries: components["schemas"]["AuditEntrySchema"][];
            /** Intact */
            intact: boolean;
            /** Brokenat */
            brokenAt?: string | null;
        };
        /**
         * AuthResponseSchema
         * @description Response payload returning user and tenant details.
         */
        AuthResponseSchema: {
            user: components["schemas"]["UserSchema"];
            tenant: components["schemas"]["TenantSchema"];
        };
        /** Body_submit_application_api_applications_post */
        Body_submit_application_api_applications_post: {
            /**
             * Payload
             * @description JSON matching IntakeIn
             */
            payload: string;
            /**
             * Files
             * @default []
             */
            files: string[];
            /**
             * File Arms
             * @default []
             */
            file_arms: string[];
            /** Face Photo */
            face_photo?: string | null;
        };
        /** CoverageIn */
        CoverageIn: {
            /** Coveragetype */
            coverageType?: string | null;
            /** Coverageamount */
            coverageAmount?: string | null;
            /** Policyterm */
            policyTerm?: string | null;
        };
        /** DatabaseHealth */
        DatabaseHealth: {
            /** Connected */
            connected: boolean;
            /**
             * Target
             * @description host:port/database being dialled, password removed.
             */
            target: string;
            /**
             * Detail
             * @description Why the connection failed.
             */
            detail?: string | null;
            /**
             * Admin Login Enabled
             * @description Whether the built-in admin sign-in works while the database is down.
             */
            admin_login_enabled: boolean;
        };
        /** DecisionIn */
        DecisionIn: {
            decision: components["schemas"]["UnderwriterDecisionType"];
            /** Finalpremium */
            finalPremium?: number | string | null;
        };
        /** DecisionSchema */
        DecisionSchema: {
            decision: components["schemas"]["UnderwriterDecisionType"];
            /** Finalpremium */
            finalPremium?: string | null;
            /**
             * Decidedat
             * Format: date-time
             */
            decidedAt: string;
            /** Underwritername */
            underwriterName?: string | null;
        };
        /** FileSchema */
        FileSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Filename */
            filename?: string | null;
            /** Mimetype */
            mimeType?: string | null;
        };
        /**
         * FindingSchema
         * @description One of the backbone's 18 findings.
         *
         *     `probability` is what the model reported; `contribution` is how much that
         *     finding actually moved the TB score. They disagree often, and the
         *     contribution is the one that explains the number.
         */
        FindingSchema: {
            /** Label */
            label: string;
            /** Probability */
            probability: number;
            /** Contribution */
            contribution: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @example {
         *       "environment": "development",
         *       "service": "HomelanderAI API",
         *       "status": "ok",
         *       "uptime_seconds": 12.34,
         *       "version": "0.1.0"
         *     }
         */
        HealthResponse: {
            /**
             * Status
             * @description Always 'ok' — a failure means no response at all.
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @description Human-readable service name.
             */
            service: string;
            /**
             * Version
             * @description API version.
             */
            version: string;
            /**
             * Environment
             * @description development | staging | production
             */
            environment: string;
            /**
             * Uptime Seconds
             * @description Seconds since this process started.
             */
            uptime_seconds: number;
        };
        /**
         * ModelInfoSchema
         * @description Provenance that has to travel with the score rather than sit in a doc —
         *     the model has only ever been tested on one hospital.
         */
        ModelInfoSchema: {
            /** Scorer */
            scorer?: string | null;
            /** Backbone */
            backbone?: string | null;
            /** Validation */
            validation?: string | null;
            /** Cvauc */
            cvAuc?: number | null;
        };
        /** NotificationSchema */
        NotificationSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Message */
            message: string;
            /** Notificationtype */
            notificationType: string;
            /** Applicationid */
            applicationId?: string | null;
            /** Reference */
            reference?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Readat */
            readAt?: string | null;
        };
        /** QueueItemSchema */
        QueueItemSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reference */
            reference: string;
            /** Applicantname */
            applicantName: string | null;
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Crs */
            crs?: number | null;
            /** Tier */
            tier?: string | null;
        };
        /** QueueSchema */
        QueueSchema: {
            /** Items */
            items: components["schemas"]["QueueItemSchema"][];
            /** Total */
            total: number;
            /** Counts */
            counts?: {
                [key: string]: number;
            };
        };
        /**
         * RegisterTenantSchema
         * @description Payload for onboarding a new carrier tenant + tenant admin.
         */
        RegisterTenantSchema: {
            /** Tenantname */
            tenantName: string;
            /**
             * Subscriptiontier
             * @default standard
             */
            subscriptionTier: string;
            /** Adminfullname */
            adminFullName: string;
            /** Adminemail */
            adminEmail: string;
            /** Adminpassword */
            adminPassword: string;
            /** Licensenumber */
            licenseNumber?: string | null;
            /** @default admin */
            role: components["schemas"]["UserRole"];
        };
        /** ScoreSchema */
        ScoreSchema: {
            /** Crs */
            crs: number;
            /** Tier */
            tier: string;
            /** Method */
            method: string;
            /** Thresholds */
            thresholds?: {
                [key: string]: unknown;
            };
            /** Visionscore */
            visionScore?: number | null;
            /**
             * Computedat
             * Format: date-time
             */
            computedAt: string;
        };
        /** SubmitResponseSchema */
        SubmitResponseSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reference */
            reference: string;
            status: components["schemas"]["ApplicationStatus"];
        };
        /**
         * TenantSchema
         * @description Tenant carrier organization representation.
         */
        TenantSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Subscriptiontier */
            subscriptionTier: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * UnderwriterDecisionType
         * @description Four actions, and deliberately no reject.
         *
         *     A model finding is grounds for a closer look, never for an automated
         *     denial — escalation to a senior underwriter is how a hard case is handled
         *     (SPEC.md §1).
         * @enum {string}
         */
        UnderwriterDecisionType: "confirmed_fast_track" | "approved_with_adjustment" | "escalated_senior_review" | "requested_additional_evidence";
        /**
         * UserLoginSchema
         * @description Sign-in details.
         *
         *     No company field: email is unique system-wide, so it identifies the account
         *     on its own.
         */
        UserLoginSchema: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserRole
         * @description User authorization roles.
         * @enum {string}
         */
        UserRole: "underwriter" | "senior_underwriter" | "admin";
        /**
         * UserSchema
         * @description User representation.
         */
        UserSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenantid
             * Format: uuid
             */
            tenantId: string;
            /** Fullname */
            fullName: string;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Licensenumber */
            licenseNumber?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_database_api_health_database_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseHealth"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_tenant_api_auth_register_tenant_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterTenantSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_applications_api_applications_get: {
        parameters: {
            query?: {
                status?: string | null;
                /** @description Match a reference or applicant name */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_application_api_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_application_api_applications_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_api_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_decision_api_applications__application_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_trail_api_applications__application_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTrailSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_files__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_api_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
