/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Can the API reach the database?
         * @description Always answers 200, even when the database is unreachable — the point is
         *     to report the state, not to fail. Use it when the database lives on another
         *     machine and you need to know whether this one can see it.
         */
        get: operations["health_database_api_health_database_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Onboard Carrier Tenant & Admin
         * @description Register a new Subscribing Carrier Tenant and initial Tenant Admin account.
         */
        post: operations["register_tenant_api_auth_register_tenant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate User & Set Session Cookie
         * @description Authenticate user with email and password, setting an httpOnly session cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Authenticated User Session
         * @description Verify current httpOnly session cookie and return user details.
         */
        get: operations["get_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout User & Clear Session Cookie
         * @description Clear httpOnly session cookie.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Profile Details
         * @description Update authenticated operator profile attributes.
         */
        patch: operations["update_profile_api_auth_profile_patch"];
        trace?: never;
    };
    "/api/auth/profile/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Account Password
         * @description Change authenticated operator password with current credential verification.
         */
        post: operations["change_password_api_auth_profile_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Carrier Tenant Staff
         * @description Retrieve all staff members associated with the caller's carrier tenant.
         */
        get: operations["list_tenant_staff_api_auth_users_get"];
        put?: never;
        /**
         * Provision New Staff Operator
         * @description Add a staff account to the caller's tenant. Administrators only.
         */
        post: operations["provision_staff_api_auth_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The plan for each risk tier, priced for a given cover
         * @description What each tier means for the policy.
         *
         *     Premiums are worked out here rather than in the dashboard so one change to
         *     `plans.py` moves every screen at once.
         */
        get: operations["get_pricing_api_pricing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Work out what each uploaded file is, before anything is scored
         * @description Identify dropped files so the operator can confirm where each one goes.
         *
         *     Stores nothing and creates no application: this runs while the operator is
         *     still filling in the form, so the review screen is instant when they submit.
         *     The kinds it proposes are only acted on after the operator confirms them.
         */
        post: operations["classify_evidence_api_evidence_classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Which models the intake form may offer, and which actually run
         * @description The form used to offer seven models as though all seven worked. One does.
         *
         *     `available` comes from the arm registry rather than a hand-kept list, so the
         *     menu cannot claim a model that would silently produce nothing.
         */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The review queue
         * @description Newest first, scoped to the signed-in user's carrier.
         */
        get: operations["list_applications_api_applications_get"];
        put?: never;
        /**
         * Submit an application with its evidence
         * @description Store the application and its evidence, then score it in the background.
         *
         *     Scoring is not done inline: model inference takes seconds, and the operator
         *     has a client sitting opposite. They get a reference immediately, and the
         *     queue shows the result when it lands.
         */
        post: operations["submit_application_api_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything the review screen needs, in one call */
        get: operations["get_application_api_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record the underwriter's decision (write-once)
         * @description One decision per application, enforced by the database.
         *
         *     The built-in admin cannot decide: `underwriter_id` is a real foreign key,
         *     and a decision has to be attributable to a person who can be held to it.
         */
        post: operations["record_decision_api_applications__application_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/turnaround": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Revise when the applicant can expect an answer
         * @description Move the expected date, with a reason the applicant will see.
         *
         *     Any underwriter on the case may do this: they are the one who knows the
         *     answer will be late, so they should be the one who can say so. The old and
         *     new dates and the reason go into the audit trail.
         */
        patch: operations["revise_turnaround_api_applications__application_id__turnaround_patch"];
        trace?: never;
    };
    "/api/applications/{application_id}/evidence-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the applicant for specific documents
         * @description Name what is missing, in the underwriter's own words.
         *
         *     Moves the application to `awaiting_evidence` and leaves the decision open:
         *     this is a pause, not an outcome. The list is what the applicant will see,
         *     so each item is stored verbatim.
         */
        post: operations["request_evidence_api_applications__application_id__evidence_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/evidence-request/{document_id}/fulfil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a requested document as received
         * @description Tick off one item. When nothing is outstanding, the application goes
         *     back to the underwriter.
         *
         *     Ticking off is not re-scoring: an existing score stands. New evidence that
         *     a model should read arrives through intake, which is what the portal
         *     upload will do.
         */
        post: operations["fulfil_evidence_request_api_applications__application_id__evidence_request__document_id__fulfil_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The audit trail, with its hash chain verified
         * @description Verification runs on every read rather than on a schedule — an audit
         *     trail nobody checks is decoration.
         */
        get: operations["get_audit_trail_api_applications__application_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve one stored image
         * @description Evidence images and heatmaps, by id.
         *
         *     Files are served through the API rather than from a static folder so that
         *     every read is checked against the caller's tenant. Health data on a public
         *     URL would be a breach whatever the filename.
         */
        get: operations["get_file_api_files__file_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Notifications
         * @description Newest first, for the signed-in user only.
         */
        get: operations["list_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_api_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenant/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This carrier's settings */
        get: operations["get_settings_api_tenant_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change this carrier's settings (admin only)
         * @description Only an administrator sets the default. The figure is what every future
         *     applicant is promised, which is a company decision rather than a case one.
         *     Applications already submitted keep the date they were given.
         */
        patch: operations["update_settings_api_tenant_settings_patch"];
        trace?: never;
    };
    "/api/portal/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Applicant sign-in */
        post: operations["portal_login_api_portal_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portal/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The applicant's own application */
        get: operations["portal_me_api_portal_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portal/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Applicant sign-out */
        post: operations["portal_logout_api_portal_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustmentSchema */
        AdjustmentSchema: {
            /** Key */
            key: string;
            /** Points */
            points: number;
            /** Reason */
            reason: string;
        };
        /** ApplicantIn */
        ApplicantIn: {
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Dateofbirth */
            dateOfBirth?: string | null;
            /** Sex */
            sex?: string | null;
            /** Email */
            email?: string | null;
        };
        /** ApplicationDetailSchema */
        ApplicationDetailSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reference */
            reference: string;
            status: components["schemas"]["ApplicationStatus"];
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
            /** Evaluatedat */
            evaluatedAt?: string | null;
            /** Expectedby */
            expectedBy?: string | null;
            /** Expectedbynote */
            expectedByNote?: string | null;
            /**
             * Overdue
             * @default false
             */
            overdue: boolean;
            applicant: components["schemas"]["ApplicantIn"];
            coverage: components["schemas"]["CoverageIn"];
            /** Modelsrequested */
            modelsRequested?: string[];
            /** Declaredhistory */
            declaredHistory?: {
                [key: string]: unknown;
            };
            score?: components["schemas"]["ScoreSchema"] | null;
            plan?: components["schemas"]["PlanSchema"] | null;
            /** Adjustments */
            adjustments?: components["schemas"]["AdjustmentSchema"][];
            /** Findings */
            findings?: components["schemas"]["FindingSchema"][];
            modelInfo?: components["schemas"]["ModelInfoSchema"] | null;
            /** Files */
            files?: components["schemas"]["FileSchema"][];
            decision?: components["schemas"]["DecisionSchema"] | null;
            /** Requesteddocuments */
            requestedDocuments?: components["schemas"]["RequestedDocumentSchema"][];
            /** Errors */
            errors?: string[];
        };
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "submitted" | "processing" | "insufficient_evidence" | "awaiting_evidence" | "scored" | "decided";
        /** AuditEntrySchema */
        AuditEntrySchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Eventtype */
            eventType: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Actorname */
            actorName?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** AuditTrailSchema */
        AuditTrailSchema: {
            /** Entries */
            entries: components["schemas"]["AuditEntrySchema"][];
            /** Intact */
            intact: boolean;
            /** Brokenat */
            brokenAt?: string | null;
        };
        /**
         * AuthResponseSchema
         * @description Response payload returning user and tenant details.
         */
        AuthResponseSchema: {
            user: components["schemas"]["UserSchema"];
            tenant: components["schemas"]["TenantSchema"];
        };
        /** Body_classify_evidence_api_evidence_classify_post */
        Body_classify_evidence_api_evidence_classify_post: {
            /**
             * Files
             * @default []
             */
            files: string[];
        };
        /** Body_submit_application_api_applications_post */
        Body_submit_application_api_applications_post: {
            /**
             * Payload
             * @description JSON matching IntakeIn
             */
            payload: string;
            /**
             * Files
             * @default []
             */
            files: string[];
            /**
             * File Arms
             * @default []
             */
            file_arms: string[];
            /**
             * File Kinds
             * @default []
             */
            file_kinds: string[];
            /** Face Photo */
            face_photo?: string | null;
        };
        /**
         * ChangePasswordSchema
         * @description Payload for updating user password with current credential verification.
         */
        ChangePasswordSchema: {
            /** Currentpassword */
            currentPassword: string;
            /** Newpassword */
            newPassword: string;
        };
        /**
         * ClassifiedFileSchema
         * @description One file as triage sees it, for the intake review screen.
         *
         *     `kind` is a proposal, not a decision. The operator confirms or corrects it
         *     before anything is scored, and `reason` is what lets them judge whether the
         *     proposal is sensible.
         */
        ClassifiedFileSchema: {
            /** Filename */
            filename: string;
            /** Kind */
            kind: string;
            /** Kindlabel */
            kindLabel: string;
            /** Reason */
            reason: string;
            /** Arms */
            arms?: string[];
            /**
             * Needschoice
             * @default false
             */
            needsChoice: boolean;
            /** Thumbnail */
            thumbnail?: string | null;
        };
        /** ClassifyResponseSchema */
        ClassifyResponseSchema: {
            /** Files */
            files: components["schemas"]["ClassifiedFileSchema"][];
            /** Choices */
            choices?: components["schemas"]["EvidenceChoiceSchema"][];
        };
        /** CoverageIn */
        CoverageIn: {
            /** Coveragetype */
            coverageType?: string | null;
            /** Coverageamount */
            coverageAmount?: string | null;
            /** Policyterm */
            policyTerm?: string | null;
        };
        /** DatabaseHealth */
        DatabaseHealth: {
            /** Connected */
            connected: boolean;
            /**
             * Target
             * @description host:port/database being dialled, password removed.
             */
            target: string;
            /**
             * Detail
             * @description Why the connection failed.
             */
            detail?: string | null;
            /**
             * Admin Login Enabled
             * @description Whether the built-in admin sign-in works while the database is down.
             */
            admin_login_enabled: boolean;
        };
        /** DecisionIn */
        DecisionIn: {
            decision: components["schemas"]["UnderwriterDecisionType"];
            /** Finalpremium */
            finalPremium?: number | string | null;
        };
        /** DecisionSchema */
        DecisionSchema: {
            decision: components["schemas"]["UnderwriterDecisionType"];
            /** Finalpremium */
            finalPremium?: string | null;
            /**
             * Decidedat
             * Format: date-time
             */
            decidedAt: string;
            /** Underwritername */
            underwriterName?: string | null;
        };
        /**
         * EvidenceChoiceSchema
         * @description One option in the correction dropdown on the review screen.
         */
        EvidenceChoiceSchema: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Arms */
            arms?: string[];
        };
        /** FileSchema */
        FileSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Filename */
            filename?: string | null;
            /** Mimetype */
            mimeType?: string | null;
        };
        /**
         * FindingSchema
         * @description One of the backbone's 18 findings.
         *
         *     `probability` is what the model reported; `contribution` is how much that
         *     finding actually moved the TB score. They disagree often, and the
         *     contribution is the one that explains the number.
         */
        FindingSchema: {
            /** Label */
            label: string;
            /** Probability */
            probability: number;
            /** Contribution */
            contribution: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @example {
         *       "environment": "development",
         *       "service": "HomelanderAI API",
         *       "status": "ok",
         *       "uptime_seconds": 12.34,
         *       "version": "0.1.0"
         *     }
         */
        HealthResponse: {
            /**
             * Status
             * @description Always 'ok' — a failure means no response at all.
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @description Human-readable service name.
             */
            service: string;
            /**
             * Version
             * @description API version.
             */
            version: string;
            /**
             * Environment
             * @description development | staging | production
             */
            environment: string;
            /**
             * Uptime Seconds
             * @description Seconds since this process started.
             */
            uptime_seconds: number;
        };
        /**
         * ModelInfoSchema
         * @description Provenance that has to travel with the score rather than sit in a doc —
         *     the model has only ever been tested on one hospital.
         */
        ModelInfoSchema: {
            /** Scorer */
            scorer?: string | null;
            /** Backbone */
            backbone?: string | null;
            /** Validation */
            validation?: string | null;
            /** Cvauc */
            cvAuc?: number | null;
        };
        /**
         * ModelSchema
         * @description One entry in the intake form's model menu.
         *
         *     `available` is derived from the arm registry, so the form can never offer a
         *     model that will not actually run.
         */
        ModelSchema: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Evidence */
            evidence: string;
            /** Screensfor */
            screensFor: string;
            /** Available */
            available: boolean;
            /** Armname */
            armName?: string | null;
            /** Armversion */
            armVersion?: string | null;
            /** Validation */
            validation?: string | null;
        };
        /** NotificationSchema */
        NotificationSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Message */
            message: string;
            /** Notificationtype */
            notificationType: string;
            /** Applicationid */
            applicationId?: string | null;
            /** Reference */
            reference?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Readat */
            readAt?: string | null;
        };
        /**
         * PlanSchema
         * @description The policy recommendation for a tier, priced for this application.
         *
         *     Illustrative, not actuarial: Idea.md gives a premium per tier but no rate
         *     card, so `baseMonthlyBdt` is the premium at `referenceCoverBdt` and
         *     `monthlyPremiumBdt` scales it to the cover actually requested. The screen
         *     says so wherever it shows a number.
         */
        PlanSchema: {
            /** Tier */
            tier: string;
            /** Name */
            name: string;
            /** Recommendation */
            recommendation: string;
            /** Humanstep */
            humanStep: string;
            /** Basemonthlybdt */
            baseMonthlyBdt?: number | null;
            /** Referencecoverbdt */
            referenceCoverBdt: number;
            /** Monthlypremiumbdt */
            monthlyPremiumBdt?: number | null;
            /**
             * Wellnessdiscounteligible
             * @default false
             */
            wellnessDiscountEligible: boolean;
        };
        /**
         * PortalCredentialsSchema
         * @description The applicant's portal sign-in, as created at intake.
         *
         *     `password` is present only when it could not be emailed, so the operator can
         *     hand it over in person. It exists here once: only its hash is stored, and no
         *     endpoint can return it again.
         */
        PortalCredentialsSchema: {
            /** Portalid */
            portalId: string;
            /** Password */
            password?: string | null;
            /**
             * Emailed
             * @default false
             */
            emailed: boolean;
            /** Email */
            email?: string | null;
        };
        /**
         * PortalDocumentSchema
         * @description One thing the underwriter has asked for, in their words.
         */
        PortalDocumentSchema: {
            /** Description */
            description: string;
            /**
             * Requestedat
             * Format: date-time
             */
            requestedAt: string;
            /** Received */
            received: boolean;
        };
        /** PortalLoginIn */
        PortalLoginIn: {
            /** Portalid */
            portalId: string;
            /** Password */
            password: string;
        };
        /**
         * PortalOfferSchema
         * @description The outcome, once a person has recorded it. Never a prediction.
         */
        PortalOfferSchema: {
            /** Outcome */
            outcome: string;
            /** Planname */
            planName?: string | null;
            /** Monthlypremiumbdt */
            monthlyPremiumBdt?: string | null;
            /**
             * Decidedat
             * Format: date-time
             */
            decidedAt: string;
        };
        /** PortalStatusSchema */
        PortalStatusSchema: {
            /** Reference */
            reference: string;
            /** Applicantname */
            applicantName?: string | null;
            /** Coveragetype */
            coverageType?: string | null;
            /** Coverageamount */
            coverageAmount?: string | null;
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
            /** Stage */
            stage: string;
            /** Stagelabel */
            stageLabel: string;
            /** Stagedetail */
            stageDetail: string;
            /** Expectedby */
            expectedBy?: string | null;
            /** Expectedbynote */
            expectedByNote?: string | null;
            /**
             * Overdue
             * @default false
             */
            overdue: boolean;
            /** Documents */
            documents?: components["schemas"]["PortalDocumentSchema"][];
            offer?: components["schemas"]["PortalOfferSchema"] | null;
        };
        /**
         * PricingSchema
         * @description The full plan table, with each tier's score band attached.
         *
         *     One response so the pricing screen cannot show a premium against the wrong
         *     band: the cut-points come from `scoring.Thresholds`, the rates from
         *     `plans.PLANS`, and neither is retyped in the dashboard.
         */
        PricingSchema: {
            /** Plans */
            plans: components["schemas"]["PlanSchema"][];
            /** Lowmax */
            lowMax: number;
            /** Moderatemax */
            moderateMax: number;
            /** Coverageamount */
            coverageAmount?: number | null;
        };
        /** QueueItemSchema */
        QueueItemSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reference */
            reference: string;
            /** Applicantname */
            applicantName: string | null;
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
            status: components["schemas"]["ApplicationStatus"];
            /** Crs */
            crs?: number | null;
            /** Tier */
            tier?: string | null;
            /** Coverageamount */
            coverageAmount?: string | null;
            /** Modelsrequested */
            modelsRequested?: string[];
            /** Expectedby */
            expectedBy?: string | null;
            /**
             * Overdue
             * @default false
             */
            overdue: boolean;
        };
        /** QueueSchema */
        QueueSchema: {
            /** Items */
            items: components["schemas"]["QueueItemSchema"][];
            /** Total */
            total: number;
            /** Counts */
            counts?: {
                [key: string]: number;
            };
        };
        /**
         * RegisterStaffSchema
         * @description A new staff account, added by an administrator of the same tenant.
         */
        RegisterStaffSchema: {
            /** Fullname */
            fullName: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** @default underwriter */
            role: components["schemas"]["UserRole"];
            /** Licensenumber */
            licenseNumber?: string | null;
        };
        /**
         * RegisterTenantSchema
         * @description Payload for onboarding a new carrier tenant + tenant admin.
         */
        RegisterTenantSchema: {
            /** Tenantname */
            tenantName: string;
            /**
             * Subscriptiontier
             * @default standard
             */
            subscriptionTier: string;
            /** Adminfullname */
            adminFullName: string;
            /** Adminemail */
            adminEmail: string;
            /** Adminpassword */
            adminPassword: string;
            /** Licensenumber */
            licenseNumber?: string | null;
            /** @default admin */
            role: components["schemas"]["UserRole"];
        };
        /**
         * RequestEvidenceIn
         * @description What the underwriter is asking the applicant for.
         *
         *     At least one item, each in plain words. "More evidence needed" with nothing
         *     named is exactly the uselessness this replaces.
         */
        RequestEvidenceIn: {
            /** Items */
            items: string[];
            /** Note */
            note?: string | null;
        };
        /** RequestedDocumentSchema */
        RequestedDocumentSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Description */
            description: string;
            /**
             * Requestedat
             * Format: date-time
             */
            requestedAt: string;
            /** Requestedbyname */
            requestedByName?: string | null;
            /** Fulfilledat */
            fulfilledAt?: string | null;
        };
        /** ScoreSchema */
        ScoreSchema: {
            /** Crs */
            crs: number;
            /** Tier */
            tier: string;
            /** Method */
            method: string;
            /** Thresholds */
            thresholds?: {
                [key: string]: unknown;
            };
            /** Visionscore */
            visionScore?: number | null;
            /**
             * Computedat
             * Format: date-time
             */
            computedAt: string;
        };
        /** SubmitResponseSchema */
        SubmitResponseSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reference */
            reference: string;
            status: components["schemas"]["ApplicationStatus"];
            portal?: components["schemas"]["PortalCredentialsSchema"] | null;
        };
        /**
         * TenantSchema
         * @description Tenant carrier organization representation.
         */
        TenantSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Subscriptiontier */
            subscriptionTier: string;
            /**
             * Turnaroundbusinessdays
             * @default 2
             */
            turnaroundBusinessDays: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** TenantSettingsIn */
        TenantSettingsIn: {
            /** Turnaroundbusinessdays */
            turnaroundBusinessDays: number;
        };
        /** TenantSettingsSchema */
        TenantSettingsSchema: {
            /** Name */
            name: string;
            /** Turnaroundbusinessdays */
            turnaroundBusinessDays: number;
        };
        /**
         * TurnaroundIn
         * @description Revise when the applicant can expect an answer.
         *
         *     The reason is required: a date that moves with no explanation is exactly
         *     the silent slip this feature exists to replace. It is stored on the
         *     application and shown to the applicant.
         */
        TurnaroundIn: {
            /**
             * Expectedby
             * Format: date
             */
            expectedBy: string;
            /** Reason */
            reason: string;
        };
        /**
         * UnderwriterDecisionType
         * @description Four actions, and deliberately no reject.
         *
         *     A model finding is grounds for a closer look, never for an automated
         *     denial — escalation to a medical professional is how a hard case is handled
         *     (SPEC.md §1).
         * @enum {string}
         */
        UnderwriterDecisionType: "confirmed_fast_track" | "approved_with_adjustment" | "escalated_senior_review" | "requested_additional_evidence";
        /**
         * UpdateProfileSchema
         * @description Payload for updating operator profile details.
         */
        UpdateProfileSchema: {
            /** Fullname */
            fullName?: string | null;
            /** Licensenumber */
            licenseNumber?: string | null;
        };
        /**
         * UserLoginSchema
         * @description Sign-in details.
         *
         *     No company field: email is unique system-wide, so it identifies the account
         *     on its own.
         */
        UserLoginSchema: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserRole
         * @description The three staff roles. There are no others.
         *
         *     Applicants are not in this list on purpose: they have no row in `users` and
         *     no role. They read their own application through the client portal with a
         *     generated portal ID and password (see `routers/portal.py`).
         *
         *     `medical_professional` was `senior_underwriter` until 2026-09-22 (migration
         *     008); what it may do did not change.
         * @enum {string}
         */
        UserRole: "underwriter" | "medical_professional" | "admin";
        /**
         * UserSchema
         * @description User representation.
         */
        UserSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenantid
             * Format: uuid
             */
            tenantId: string;
            /** Fullname */
            fullName: string;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Licensenumber */
            licenseNumber?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_database_api_health_database_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseHealth"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_tenant_api_auth_register_tenant_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterTenantSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    update_profile_api_auth_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_auth_profile_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tenant_staff_api_auth_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_staff_api_auth_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterStaffSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pricing_api_pricing_get: {
        parameters: {
            query?: {
                /** @description Sum assured in BDT; premiums scale from it */
                coverage?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classify_evidence_api_evidence_classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_classify_evidence_api_evidence_classify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_applications_get: {
        parameters: {
            query?: {
                status?: string | null;
                /** @description Match a reference or applicant name */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_application_api_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_application_api_applications_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_api_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_decision_api_applications__application_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_turnaround_api_applications__application_id__turnaround_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnaroundIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_evidence_api_applications__application_id__evidence_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestEvidenceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestedDocumentSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fulfil_evidence_request_api_applications__application_id__evidence_request__document_id__fulfil_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                document_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestedDocumentSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_trail_api_applications__application_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTrailSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_files__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_notifications_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_api_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_tenant_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSettingsSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_api_tenant_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSettingsSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portal_login_api_portal_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalStatusSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portal_me_api_portal_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                portal_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalStatusSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portal_logout_api_portal_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
